# -*- coding: utf-8 -*-
"""Analise de Planejamento CRO 5 v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZNbRmzUL3Fnw82SO1MclF_SW8dJGBOD

# Analise de Planejamento de Projetos da CRO 5 #

## Importações de Bibliotecas
"""

import subprocess, sys

def instalar(pacote):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pacote])

try:
    import openpyxl
except ImportError:
    instalar("openpyxl")

import warnings, json, os
from pathlib import Path
from io import BytesIO

import numpy as np
import pandas as pd


from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Lasso, ElasticNet
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import LeaveOneOut, cross_val_score
from sklearn.inspection import permutation_importance

warnings.filterwarnings("ignore")

"""## Configurações"""

# Detecta ambiente (Colab = online ou offline)

EM_COLAB = False
try:
    from google.colab import files as colab_files
    from IPython.display import display, HTML as IPY_HTML
    EM_COLAB = True
    print("✅  Ambiente Google Colab detectado.")
except ImportError:
    print("ℹ️   Executando fora do Colab (modo local).")

# Configura paleta de cores

AZUL     = "#1B3A5C"
LARANJA  = "#E8490F"
VERDE    = "#2E8B57"
AMARELO  = "#F4C430"
CINZA    = "#6C757D"
PALETA   = [AZUL, LARANJA, VERDE, AMARELO, CINZA,
            "#8B1A4A", "#3A7CA5", "#FF8C00", "#009688"]

# Mapeamento de colunas

NOMES_COLUNAS = [
    "id","om","projeto","area","benfeitoria","tipo_om","tipo_obra",
    "n_disc",        # col 8 — Qtd disciplinas de engenharia no PE
    "arq_reaprov",   # col 9 — 0=projeto único | 1=reutiliza arquitetura existente
    "pts_prev","pts_real",
    "ep_prev","ep_exec","ap_prev","ap_exec",
    "pe_arq_prev","pe_arq_exec","pe_eng_prev","pe_eng_exec",
    "orc_prev","orc_exec",
    "dt_inicio","sprint_prev","dt_termino","sprint_exec",
]

# Threshold mínimo de projetos com flag=1 para incluir a feature no LOO-CV.
# Abaixo disso, o LOO não tem amostras suficientes para aprender o padrão,
# mas a feature ainda é usada corretamente na PREDIÇÃO de novos projetos.
COL_ARQ_REAPROV = "arq_reaprov"
THRESHOLD_ARQ_REAPROV = 3

ETAPAS = {
    "EP":     ("ep_prev",     "ep_exec"),
    "AP":     ("ap_prev",     "ap_exec"),
    "PE Arq": ("pe_arq_prev", "pe_arq_exec"),
    "PE Eng": ("pe_eng_prev", "pe_eng_exec"),
    "Orc":    ("orc_prev",    "orc_exec"),
}

ETAPAS_LABEL = {
    "EP":     "Estudo Preliminar",
    "AP":     "Anteprojeto",
    "PE Arq": "PE Arquitetura",
    "PE Eng": "PE Engenharia",
    "Orc":    "Orçamento",
}

"""## Carrega Dataset"""

def carregar_dados() -> pd.DataFrame:
    """Upload e carregamento do Excel. Funciona no Colab e localmente."""
    if EM_COLAB:
        print("\n📂 Selecione o arquivo Excel do dataset:")
        uploaded = colab_files.upload()
        if not uploaded:
            raise ValueError("Nenhum arquivo enviado.")
        nome_arquivo = list(uploaded.keys())[0]
        conteudo = BytesIO(uploaded[nome_arquivo])
    else:
        import glob
        xlsx_files = glob.glob("*.xlsx")
        if not xlsx_files:
            raise FileNotFoundError(
                "Nenhum .xlsx encontrado. "
                "Coloque o arquivo na mesma pasta e rode novamente."
            )
        nome_arquivo = xlsx_files[0]
        conteudo = nome_arquivo
        print(f"📂 Arquivo encontrado: {nome_arquivo}")

    df = pd.read_excel(conteudo)

    if len(df.columns) < len(NOMES_COLUNAS):
        raise ValueError(
            f"Esperadas {len(NOMES_COLUNAS)} colunas, encontradas {len(df.columns)}."
        )

    n_base = len(NOMES_COLUNAS)  # 24 colunas
    colunas_extra = list(df.columns[n_base:])
    df.columns = NOMES_COLUNAS + colunas_extra

    for col in ("dt_inicio", "dt_termino"):
        df[col] = pd.to_datetime(df[col], dayfirst=True, errors="coerce")

    cols_num = [c for c in NOMES_COLUNAS
                if c not in ("id","om","projeto","benfeitoria",
                             "tipo_om","tipo_obra","dt_inicio","dt_termino")]
    for col in cols_num:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df[COL_ARQ_REAPROV] = pd.to_numeric(
        df[COL_ARQ_REAPROV], errors="coerce").fillna(0).astype(int)

    df = df.dropna(subset=["pts_prev","pts_real"]).reset_index(drop=True)

    n_reaprov = df[COL_ARQ_REAPROV].sum()
    status_flag = (f"✅ {n_reaprov} projeto(s) — LOO ativo"
                   if n_reaprov >= THRESHOLD_ARQ_REAPROV
                   else f"⏳ {n_reaprov}/{THRESHOLD_ARQ_REAPROV} — salvo para predição")
    print(f"✅  Dataset carregado: {len(df)} projetos | {len(df.columns)} colunas")
    print(f"   Arquitetura reaproveitada: {status_flag}\n")
    return df

"""## Feature Eng e Modelos de Predição"""

def engenharia_features(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["duracao_dias"]    = (df["dt_termino"] - df["dt_inicio"]).dt.days.clip(lower=0)
    df["var_pts_pct"]     = ((df["pts_real"] - df["pts_prev"]) / df["pts_prev"].replace(0, np.nan)) * 100
    df["var_sprint_pct"]  = ((df["sprint_exec"] - df["sprint_prev"]) / df["sprint_prev"].replace(0, np.nan)) * 100
    df["idx_eficiencia"]  = df["pts_real"] / df["pts_prev"].replace(0, np.nan)
    df["vel_prevista"]    = df["pts_prev"] / df["sprint_prev"].replace(0, np.nan)
    df["vel_realizada"]   = df["pts_real"] / df["sprint_exec"].replace(0, np.nan)

    for chave, (prev, exec_) in ETAPAS.items():
        col = chave.lower().replace(" ", "_")
        df[f"var_{col}_abs"] = df[exec_] - df[prev]
        df[f"var_{col}_pct"] = (df[f"var_{col}_abs"] / df[prev].replace(0, np.nan)) * 100
        df[f"prop_{col}"]    = df[exec_] / df["pts_real"].replace(0, np.nan)

    return df

def preparar_features(df: pd.DataFrame):
    """
    Modelo 1 - Predicao de DURACAO (retrospectivo).
    Features: dados realmente executados em projetos anteriores.
    Targets : sprint_exec, duracao_dias.
    """
    df = df.copy()
    encoders = {}
    for col in ("benfeitoria", "tipo_om", "tipo_obra"):
        le = LabelEncoder()
        df[f"{col}_enc"] = le.fit_transform(df[col].fillna("desconhecido"))
        encoders[col] = le

    # Features: tudo executado (sem sprint_exec, que e target)
    # arq_reaprov incluído diretamente — projetos com arquitetura
    # reaproveitada têm duração sistematicamente menor.
    feature_cols = [
        "area",
        "pts_real",
        "ep_exec",
        "ap_exec",
        "pe_arq_exec",
        "pe_eng_exec",
        "orc_exec",
        "benfeitoria_enc",
        "tipo_om_enc",
        "tipo_obra_enc",
        COL_ARQ_REAPROV,
    ]
    feature_cols = [c for c in feature_cols if c in df.columns]
    encoders["feature_cols"] = feature_cols

    X         = df[feature_cols].fillna(0)
    y_sprints = df["sprint_exec"].fillna(0)
    y_dias    = df["duracao_dias"]
    return X, y_sprints, y_dias, encoders

def preparar_features_planejamento(df: pd.DataFrame, encoders: dict):
    """
    Modelo 2 - Estimativa de PLANEJAMENTO (multi-output).

    Features base : area + tipo_obra  (melhor combinação LOO-CV)
    Feature condicional: arq_reaprov — incluída no LOO apenas quando
      n(flag=1) >= THRESHOLD_ARQ_REAPROV; sempre usada na predição de novos projetos.

    Targets: pts_prev total + pontos previstos por etapa.
    """
    df = df.copy()

    # Recodificar com encoders do Modelo 1 (garantia de consistência)
    for col in ("benfeitoria", "tipo_om", "tipo_obra"):
        enc = encoders.get(col)
        if enc:
            df[f"{col}_enc"] = enc.transform(df[col].fillna("desconhecido"))

    n_reaprov = int(df[COL_ARQ_REAPROV].sum()) if COL_ARQ_REAPROV in df.columns else 0
    usar_flag_loo = n_reaprov >= THRESHOLD_ARQ_REAPROV

    # Features para LOO-CV (treino/avaliação)
    feat_plan_loo = ["area", "tipo_obra_enc"]
    if usar_flag_loo:
        feat_plan_loo.append(COL_ARQ_REAPROV)

    # Features para predição de novos projetos (sempre inclui a flag)
    feat_plan_pred = ["area", "tipo_obra_enc", COL_ARQ_REAPROV]
    if "n_disc" in df.columns:
        feat_plan_pred.append("n_disc")
    feat_plan_pred = [c for c in feat_plan_pred if c in df.columns]

    if not usar_flag_loo and n_reaprov > 0:
        print(f"   ℹ️  arq_reaprov: {n_reaprov}/{THRESHOLD_ARQ_REAPROV} projetos — "
              f"excluída do LOO, ativa na predição de novos projetos.")

    alvos_plan = ["pts_prev", "ep_prev", "ap_prev",
                  "pe_arq_prev", "pe_eng_prev", "orc_prev"]
    alvos_plan = [c for c in alvos_plan if c in df.columns]

    X_plan_loo  = df[feat_plan_loo].fillna(0)
    X_plan_pred = df[feat_plan_pred].fillna(0)
    Y_plan      = df[alvos_plan].fillna(0)

    return X_plan_loo, X_plan_pred, Y_plan, feat_plan_loo, feat_plan_pred, alvos_plan

def _loo_metricas(modelo, X, y):
    """
    Calcula MAE, RMSE e R² (LOO-Q²) com LOO-CV acumulado.

    cross_val_score com LOO tem n=1 por fold: RMSE=MAE e R²=NaN por fold.
    Solução correta: acumular todos os resíduos e calcular globalmente.
      R² = 1 - SS_res / SS_tot  (Q² ou LOO-R²; pode ser negativo)
    """
    from sklearn.base import clone
    y_arr  = np.array(y, dtype=float)
    X_val  = X.values if hasattr(X, "values") else np.array(X)
    y_pred = np.zeros(len(y_arr))
    for tr, te in LeaveOneOut().split(X_val):
        m_tmp = clone(modelo)
        m_tmp.fit(X_val[tr], y_arr[tr])
        y_pred[te] = m_tmp.predict(X_val[te])
    res    = y_arr - y_pred
    mae    = float(np.mean(np.abs(res)))
    rmse   = float(np.sqrt(np.mean(res ** 2)))
    ss_res = float(np.sum(res ** 2))
    ss_tot = float(np.sum((y_arr - y_arr.mean()) ** 2))
    r2     = float(1 - ss_res / ss_tot) if ss_tot > 1e-10 else float("nan")
    abs_res = np.abs(res)
    mediana = float(np.median(abs_res))
    dp      = float(np.std(abs_res, ddof=1))
    return round(mae, 3), round(rmse, 3), round(r2, 3), round(mediana, 3), round(dp, 3)

def treinar_modelos(X, y, alvo):
    """Avalia modelos com LOO-CV e retorna resultados + melhor modelo treinado."""
    print(f"\n🤖 Predição: {alvo}")
    idx = y.dropna().index
    Xv, yv = X.loc[idx], y.loc[idx]

    if len(yv) < 4:
        print("  ⚠️  Amostras insuficientes (< 4). Pulando predição.")
        return {}, None, None

    modelos = {
        "Ridge":             Pipeline([("sc", StandardScaler()), ("m", Ridge(alpha=1.0))]),
        "Lasso":             Pipeline([("sc", StandardScaler()), ("m", Lasso(alpha=0.5, max_iter=5000))]),
        "ElasticNet":        Pipeline([("sc", StandardScaler()), ("m", ElasticNet(alpha=0.5, max_iter=5000))]),
        "SVR":               Pipeline([("sc", StandardScaler()), ("m", SVR(kernel="rbf", C=10))]),
        "KNN":               Pipeline([("sc", StandardScaler()), ("m", KNeighborsRegressor(n_neighbors=min(3, len(yv)-1)))]),
        "Random Forest":     RandomForestRegressor(n_estimators=100, random_state=42, max_depth=3),
        "Grad. Boosting":    GradientBoostingRegressor(n_estimators=50, random_state=42, max_depth=2),
    }

    resultados = {}
    for nome, m in modelos.items():
        mae, rmse, r2, mediana, dp = _loo_metricas(m, Xv, yv)
        resultados[nome] = {"MAE": mae, "RMSE": rmse, "R2": r2, "Mediana": mediana, "DP": dp}
        print(f"   {nome:20s}  MAE={mae:.2f}  RMSE={rmse:.2f}  Mediana={mediana:.2f}  DP={dp:.2f}  R²={r2:+.3f}")

    melhor_nome = min(resultados, key=lambda k: resultados[k]["MAE"])
    print(f"   ⭐ Melhor (MAE): {melhor_nome} "
          f"(MAE={resultados[melhor_nome]['MAE']:.2f}  "
          f"R²={resultados[melhor_nome]['R2']:+.3f})")

    melhor = modelos[melhor_nome]
    melhor.fit(Xv, yv)

    # Sempre treinar Ridge separado para exportar coeficientes ao HTML
    ridge = Pipeline([("sc", StandardScaler()), ("m", Ridge(alpha=1.0))])
    ridge.fit(Xv, yv)
    scaler   = ridge.named_steps["sc"]
    ridge_m  = ridge.named_steps["m"]
    coef_info = {
        "intercept":  float(ridge_m.intercept_),
        "coef":       ridge_m.coef_.tolist(),
        "mean":       scaler.mean_.tolist(),
        "scale":      scaler.scale_.tolist(),
        "features":   list(Xv.columns),
    }

    return resultados, (melhor_nome, melhor), coef_info

def treinar_modelo_planejamento(X_plan_loo, X_plan_pred, Y_plan,
                                feat_plan_loo, feat_plan_pred, alvos_plan):
    X_plan  = X_plan_loo    # alias para o LOO-CV
    feat_plan = feat_plan_loo
    """
    Modelo 2: estimativa de planejamento multi-output com LOO-CV.
    Estrategia: avalia cada alvo univariado com LOO-CV, depois treina
    MultiOutputRegressor final em todos os dados.
    Exporta coeficientes Ridge por alvo para predicao no browser (JS).
    """
    from sklearn.multioutput import MultiOutputRegressor

    print("\n🗂️  Modelo de Planejamento (multi-output):")
    print(f"   Features : {feat_plan}")
    print(f"   Alvos    : {alvos_plan}")

    idx = Y_plan.dropna(how="all").index
    Xv  = X_plan.loc[idx]
    Yv  = Y_plan.loc[idx]

    if len(Yv) < 4:
        print("  Amostras insuficientes. Pulando.")
        return {}, None, None

    scaler_plan = StandardScaler()
    Xv_sc = scaler_plan.fit_transform(Xv)

    loo = LeaveOneOut()

    # Candidatos: avaliados por media de MAE sobre todos os alvos (LOO-CV univariado)
    candidatos = {
        "Ridge":       Ridge(alpha=1.0),
        "Lasso":       Lasso(alpha=0.5, max_iter=5000),
        "ElasticNet":  ElasticNet(alpha=0.5, max_iter=5000),
        "KNN (k=3)":   KNeighborsRegressor(n_neighbors=min(3, len(Yv)-1)),
    }

    def _metricas_por_alvo(modelo, Xv, Yv, alvos_plan):
        """MAE, RMSE e R² médios via LOO acumulado por alvo."""
        maes, rmses, r2s, medianas, dps = [], [], [], [], []
        for alvo in alvos_plan:
            mae, rmse, r2, mediana, dp = _loo_metricas(modelo, Xv, Yv[alvo])
            maes.append(mae); rmses.append(rmse); r2s.append(r2)
            medianas.append(mediana); dps.append(dp)
        return (round(float(np.mean(maes)),    3),
                round(float(np.mean(rmses)),   3),
                round(float(np.nanmean(r2s)),  3),
                round(float(np.mean(medianas)),3),
                round(float(np.mean(dps)),     3))

    resultados_plan = {}
    for nome, est in candidatos.items():
        pipe = Pipeline([("sc", StandardScaler()), ("m", est)])
        mae, rmse, r2, mediana, dp = _metricas_por_alvo(pipe, Xv, Yv, alvos_plan)
        resultados_plan[nome] = {"MAE": mae, "RMSE": rmse, "R2": r2, "Mediana": mediana, "DP": dp}
        print(f"   {nome:14s}  MAE={mae:.2f}  RMSE={rmse:.2f}  Mediana={mediana:.2f}  DP={dp:.2f}  R²={r2:+.3f}")

    # Random Forest (multi-output nativo, avaliado por alvo)
    rf_pipe = Pipeline([("sc", StandardScaler()),
                        ("m", RandomForestRegressor(n_estimators=100,
                                                    random_state=42, max_depth=3))])
    mae_rf, rmse_rf, r2_rf, med_rf, dp_rf = _metricas_por_alvo(rf_pipe, Xv, Yv, alvos_plan)
    resultados_plan["Random Forest"] = {"MAE": mae_rf, "RMSE": rmse_rf, "R2": r2_rf, "Mediana": med_rf, "DP": dp_rf}
    print(f"   {'Random Forest':14s}  MAE={mae_rf:.2f}  RMSE={rmse_rf:.2f}  Mediana={mediana:.2f}  DP={dp:.2f}  R²={r2:+.3f}")

    melhor_nome = min(resultados_plan, key=lambda k: resultados_plan[k]["MAE"])
    print(f"   ⭐ Melhor (MAE): {melhor_nome}  "
          f"MAE={resultados_plan[melhor_nome]['MAE']:.2f}  "
          f"R²={resultados_plan[melhor_nome]['R2']:+.3f}")

    # Treinar MultiOutputRegressor final em todos os dados
    base = (RandomForestRegressor(n_estimators=100, random_state=42, max_depth=3)
            if melhor_nome == "Random Forest"
            else Pipeline([("sc", StandardScaler()),
                           ("m", candidatos.get(melhor_nome, Ridge(alpha=1.0)))]))
    melhor_multi = MultiOutputRegressor(base)
    melhor_multi.fit(Xv, Yv)

    # Serializar Ridge por alvo para predicao client-side (JS)
    # Usa feat_plan_pred (sempre inclui arq_reaprov)
    idx_pred = Y_plan.dropna(how="all").index
    Xv_pred  = X_plan_pred.loc[idx_pred]
    scaler_pred = StandardScaler().fit(Xv_pred)
    Xv_pred_sc  = scaler_pred.transform(Xv_pred)

    coef_plan = {
        "alvos":    alvos_plan,
        "features": feat_plan_pred,
        "mean":     scaler_pred.mean_.tolist(),
        "scale":    scaler_pred.scale_.tolist(),
        "modelos":  {}
    }
    for alvo in alvos_plan:
        if alvo == "pe_eng_prev" and "n_disc" in X_plan_pred.columns:
            feat_pe = [c for c in feat_plan_pred if c in X_plan_pred.columns]
            Xpe = X_plan_pred.loc[idx_pred, feat_pe].fillna(0)
            sc_pe = StandardScaler().fit(Xpe)
            r_pe = Ridge(alpha=1.0).fit(sc_pe.transform(Xpe), Yv[alvo])
            coef_plan["modelos"][alvo] = {
                "intercept": float(r_pe.intercept_), "coef": r_pe.coef_.tolist(),
                "features": feat_pe, "mean": sc_pe.mean_.tolist(), "scale": sc_pe.scale_.tolist(),
            }
        else:
            r = Ridge(alpha=1.0).fit(Xv_pred_sc, Yv[alvo])
            coef_plan["modelos"][alvo] = {
                "intercept": float(r.intercept_), "coef": r.coef_.tolist(),
            }

    return resultados_plan, (melhor_nome, melhor_multi), coef_plan

def fig_planejamento_multioutput(df, coef_plan):
    """Barras comparando pts_prev real vs predito pelo Ridge por etapa."""
    if not coef_plan:
        return go.Figure()

    alvos  = coef_plan["alvos"]
    mean_  = np.array(coef_plan["mean"])
    scale_ = np.array(coef_plan["scale"])

    # Reconstruir predicoes para cada projeto
    feat_plan = coef_plan["features"]
    # Encode categorias para os projetos existentes (usar valores medianos como proxy)
    medias_prev  = [df[a].mean() if a in df.columns else 0 for a in alvos]
    medias_pred  = []
    for alvo in alvos:
        mc = coef_plan["modelos"][alvo]
        # Media dos inputs (area media, 0 para categoricas)
        x_medio = np.zeros(len(feat_plan))
        for i, f in enumerate(feat_plan):
            if f == "area":
                x_medio[i] = df["area"].mean() if "area" in df.columns else 0
        x_norm = (x_medio - mean_) / (scale_ + 1e-9)
        pred = mc["intercept"] + float(np.dot(mc["coef"], x_norm))
        medias_pred.append(max(0, pred))

    labels = {
        "pts_prev":    "Total",
        "ep_prev":     "EP",
        "ap_prev":     "AP",
        "pe_arq_prev": "PE Arq",
        "pe_eng_prev": "PE Eng",
        "orc_prev":    "Orçamento",
    }
    nomes = [labels.get(a, a) for a in alvos]

    fig = go.Figure()
    fig.add_trace(go.Bar(
        name="Média Real (previsto histórico)",
        x=nomes, y=medias_prev,
        marker_color=AZUL,
        hovertemplate="<b>%{x}</b><br>Média histórica: %{y:.1f} pts<extra></extra>",
    ))
    fig.add_trace(go.Bar(
        name="Estimativa do Modelo (Ridge)",
        x=nomes, y=medias_pred,
        marker_color=LARANJA,
        hovertemplate="<b>%{x}</b><br>Estimativa Ridge: %{y:.1f} pts<extra></extra>",
    ))
    fig.update_layout(
        barmode="group",
        title="<b>Modelo de Planejamento — Média Histórica vs Estimativa Ridge</b>",
        yaxis_title="Pontos",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        legend=dict(orientation="h", yanchor="bottom", y=1.02),
    )
    return fig

def fig_comparacao_modelos_plan(res_sprints, res_dias, res_plan):
    """Barras comparando MAE dos modelos para os três alvos."""
    subtitles = ["Sprints (LOO-CV MAE)", "Duração — dias (LOO-CV MAE)",
                 "Planejamento — MAE médio por etapa"]
    fig = make_subplots(rows=1, cols=3, subplot_titles=subtitles)

    for col_idx, (res, unid) in enumerate(
        [(res_sprints, "sprint"), (res_dias, "dia"), (res_plan, "pts")], 1
    ):
        if not res:
            continue
        nomes = list(res.keys())
        maes  = list(res.values())
        melhor_idx = maes.index(min(maes))
        cores = [VERDE if i == melhor_idx else AZUL for i in range(len(nomes))]
        fig.add_trace(go.Bar(
            x=maes, y=nomes,
            orientation="h",
            marker_color=cores,
            text=[f"{v:.1f}" for v in maes],
            textposition="outside",
            showlegend=False,
        ), row=1, col=col_idx)

    fig.update_layout(
        title="<b>Comparação de Modelos — LOO-CV (verde = melhor)</b>",
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        height=380,
    )
    return fig

"""## KPI"""

def calcular_kpis(df: pd.DataFrame) -> dict:
    kpis = {
        "n_projetos":          int(len(df)),
        "var_pts_media":       round(float(df["var_pts_pct"].mean()), 1),
        "var_sprint_media":    round(float(df["var_sprint_pct"].mean()), 1),
        "pct_estourou_pontos": round(float((df["var_pts_pct"] > 0).mean() * 100), 1),
        "pct_estourou_sprint": round(float((df["var_sprint_pct"] > 0).mean() * 100), 1),
        "duracao_media":       round(float(df["duracao_dias"].mean()), 0),
        "idx_efic_media":      round(float(df["idx_eficiencia"].mean()), 2),
    }
    etapa_var = {}
    for chave in ETAPAS:
        col = f"var_{chave.lower().replace(' ','_')}_pct"
        if col in df.columns:
            etapa_var[chave] = df[col].mean()
    if etapa_var:
        pior = max(etapa_var, key=etapa_var.get)
        kpis["pior_etapa"]     = ETAPAS_LABEL[pior]
        kpis["pior_etapa_var"] = round(etapa_var[pior], 1)
    return kpis

"""## Cálculo estimado para novos projetos"""

def treinar_modelo_duracao_pre(df: pd.DataFrame, encoders: dict):
    """
    Modelo de duração com features disponíveis ANTES de começar o projeto.
    Features: área + benfeitoria + tipo_om + tipo_obra + arq_reaprov.
    Alvos   : sprint_exec, duracao_dias.
    Serializa coeficientes Ridge para predição client-side no HTML.
    """
    from sklearn.multioutput import MultiOutputRegressor

    df = df.copy()
    for col in ("benfeitoria", "tipo_om", "tipo_obra"):
        enc = encoders.get(col)
        if enc:
            df[f"{col}_enc"] = enc.transform(df[col].fillna("desconhecido"))

    feat_pre = ["area", "benfeitoria_enc", "tipo_om_enc",
                "tipo_obra_enc", COL_ARQ_REAPROV]
    feat_pre = [c for c in feat_pre if c in df.columns]

    print(f"\n⏱️  Modelo Duração Pré-Projeto:")
    print(f"   Features: {feat_pre}")

    coefs_dur = {}
    for alvo in ["sprint_exec", "duracao_dias"]:
        y = df[alvo].dropna()
        Xv = df.loc[y.index, feat_pre].fillna(0)

        if len(y) < 4:
            print(f"   ⚠️  {alvo}: amostras insuficientes")
            continue

        # Avaliar com LOO-CV acumulado (MAE ≠ RMSE, R² válido)
        pipe = Pipeline([("sc", StandardScaler()), ("m", Ridge(alpha=1.0))])
        mae, rmse, r2, mediana, dp = _loo_metricas(pipe, Xv, y)
        print(f"   {alvo:15s}  MAE={mae:.2f}  RMSE={rmse:.2f}  R²={r2:+.3f}  "
              f"({mae / y.mean() * 100:.1f}% da média)")

        # Treinar Ridge final para serializar
        sc_ = StandardScaler().fit(Xv)
        r   = Ridge(alpha=1.0)
        r.fit(sc_.transform(Xv), y)
        coefs_dur[alvo] = {
            "intercept": float(r.intercept_),
            "coef":      r.coef_.tolist(),
            "mean":      sc_.mean_.tolist(),
            "scale":     sc_.scale_.tolist(),
            "features":  feat_pre,
        }

    return coefs_dur

"""## Motor de analogia"""

_AP_REGRA = {
    "Adequação - Tipo 1": "nunca",
    "Adequação - Tipo 2": "raramente",
    "Construção": "frequente",
    "Reforma": "sempre",
}
# LOO-CV MAE relativo verificado nos 14 projetos (alvo *_prev, Lasso)
_CONFIANCA = {
    "EP":     {"mae_rel": 46, "cor": "yellow", "label": "Moderada"},
    "AP":     {"mae_rel": 92, "cor": "red",    "label": "Baixa"},
    "PE Arq": {"mae_rel": 27, "cor": "green",  "label": "Alta"},
    "PE Eng": {"mae_rel": 36, "cor": "yellow", "label": "Moderada"},
    "Orc":    {"mae_rel": 37, "cor": "yellow", "label": "Moderada"},
}
_ET_EXEC = [("EP","ep_exec"),("AP","ap_exec"),("PE Arq","pe_arq_exec"),
            ("PE Eng","pe_eng_exec"),("Orc","orc_exec")]
_ET_PREV = [("EP","ep_prev"),("AP","ap_prev"),("PE Arq","pe_arq_prev"),
            ("PE Eng","pe_eng_prev"),("Orc","orc_prev")]


class MotorAnalogia:
    def __init__(self):
        self.df = None; self._encs = {}
        self.area_min = self.area_max = 0.0; self._vecs = []

    def fit(self, df):
        self.df = df.copy().reset_index(drop=True)
        for col in ("tipo_obra","benfeitoria","tipo_om"):
            vals = sorted(self.df[col].dropna().unique().tolist())
            self._encs[col] = {v: i for i, v in enumerate(vals)}
        areas = self.df["area"].dropna()
        self.area_min, self.area_max = float(areas.min()), float(areas.max())
        self._vecs = [self._vec(r.to_dict()) for _, r in self.df.iterrows()]
        return self

    def _vec(self, row):
        v = []
        for col, peso in [("tipo_obra",3.0),("benfeitoria",2.0),("tipo_om",1.0)]:
            n = len(self._encs[col]); oh = [0.0]*n
            val = row.get(col)
            if val in self._encs[col]: oh[self._encs[col][val]] = 1.0
            v.extend(x*peso for x in oh)
        rng = self.area_max - self.area_min
        area_n = (float(row.get("area") or 0)-self.area_min)/rng if rng else 0.5
        v.append(area_n*2.0)
        nd = float(row.get("n_disc") or 4)
        v.append(max(0.0, min(1.0,(nd-2)/6))*2.0)
        v.append(float(row.get("arq_reaprov") or 0)*0.5)
        return np.array(v, dtype=float)

    @staticmethod
    def _cos(a, b):
        na, nb = np.linalg.norm(a), np.linalg.norm(b)
        return float(np.dot(a,b)/(na*nb)) if na>0 and nb>0 else 0.0

    def similares(self, query, k=3, excluir=None):
        qv = self._vec(query)
        sims = [(i,self._cos(qv,v)) for i,v in enumerate(self._vecs)
                if excluir is None or i not in excluir]
        sims.sort(key=lambda x:-x[1])
        return [(i,s,self.df.iloc[i]) for i,s in sims[:k]]

    def predizer(self, query, k=3, excluir=None):
        sims = self.similares(query, k=k, excluir=excluir)
        if not sims: return None, []
        tw = sum(s for _,s,_ in sims) or 1.0
        pred = {"pts_real":0.0, "sprint_exec_media":0.0}
        for _,col in _ET_EXEC: pred[col] = 0.0
        for (_,s,row) in sims:
            w = s/tw
            pred["pts_real"] += w*float(row.get("pts_real") or 0)
            pred["sprint_exec_media"] += w*float(row.get("sprint_exec") or 0)
            for _,col in _ET_EXEC: pred[col] += w*float(row.get(col) or 0)
        # AP condicional
        if _AP_REGRA.get(query.get("tipo_obra",""),"frequente") in ("nunca","raramente"):
            pred["ap_exec"] = 0.0
        return pred, sims

    def alertas_por_tipo(self):
        result = {}
        for tp in self._encs["tipo_obra"]:
            result[tp] = {}
            sub = self.df[self.df["tipo_obra"]==tp]
            for label,(pc,ec) in zip(["EP","AP","PE Arq","PE Eng","Orc"],
                                      [(p,e) for (_,p),(_,e) in zip(_ET_PREV,_ET_EXEC)]):
                s = sub[sub[pc]>0]
                if not len(s): continue
                v = ((s[ec]-s[pc])/s[pc]*100).values
                result[tp][label] = {
                    "media_var": round(float(np.mean(v)),1),
                    "pct_estouro": round(float(np.mean(v>0)*100),0),
                    "n": int(len(s)),
                }
        return result

    def loo_mae(self, k=3):
        erros = {"pts_real":[], "sprint_exec_media":[]}
        for _,col in _ET_EXEC: erros[col] = []
        for i,(_,row) in enumerate(self.df.iterrows()):
            pred,_ = self.predizer(row.to_dict(), k=k, excluir={i})
            if pred is None: continue
            erros["pts_real"].append(abs(pred["pts_real"]-float(row.get("pts_real") or 0)))
            erros["sprint_exec_media"].append(abs(pred["sprint_exec_media"]-float(row.get("sprint_exec") or 0)))
            for _,col in _ET_EXEC:
                erros[col].append(abs(pred[col]-float(row.get(col) or 0)))
        return {k:round(float(np.mean(v)),2) for k,v in erros.items() if v}

    def exportar_js(self):
        projetos = []
        for _,row in self.df.iterrows():
            p = {
                "id":int(row.get("id",0)), "om":str(row.get("om","")),
                "proj":str(row.get("projeto",""))[:40],
                "area":round(float(row.get("area") or 0),1),
                "tipo_obra":str(row.get("tipo_obra","")),
                "benfeitoria":str(row.get("benfeitoria","")),
                "tipo_om":str(row.get("tipo_om","")),
                "n_disc":int(row.get("n_disc") or 4),
                "arq_reaprov":int(row.get("arq_reaprov") or 0),
                "pts_real":float(row.get("pts_real") or 0),
                "sprint_exec":int(row.get("sprint_exec") or 0),
            }
            for _,col in _ET_EXEC: p[col] = float(row.get(col) or 0)
            projetos.append(p)
        return {
            "encs":     {k:v for k,v in self._encs.items()},
            "n_feats":  {k:len(v) for k,v in self._encs.items()},
            "area_min": self.area_min, "area_max": self.area_max,
            "vecs":     [v.tolist() for v in self._vecs],
            "projetos": projetos,
            "loo_mae":  self.loo_mae(),
            "alertas":  self.alertas_por_tipo(),
            "confianca":_CONFIANCA,
            "ap_regra": _AP_REGRA,
        }

def construir_dados_anuais(df: pd.DataFrame) -> dict:
    df2 = df.copy()
    df2["_ano"] = pd.to_datetime(df2["dt_inicio"], errors="coerce").dt.year
    anos = sorted(df2["_ano"].dropna().unique().astype(int))
    if not anos: return {}
    por_ano = {}
    for ano in anos:
        g = df2[df2["_ano"]==ano]
        var_et = {}
        for label,(pc,ec) in zip(["EP","AP","PE Arq","PE Eng","Orc"],
                                  [(p,e) for (_,p),(_,e) in zip(_ET_PREV,_ET_EXEC)]):
            s = g[g[pc]>0]
            if len(s): var_et[label] = round(float(((s[ec]-s[pc])/s[pc]*100).mean()),1)
        vp = ((g["pts_real"]-g["pts_prev"])/g["pts_prev"]*100)
        vs = ((g["sprint_exec"]-g["sprint_prev"])/g["sprint_prev"]*100)
        por_ano[str(ano)] = {
            "n": int(len(g)),
            "var_pts":    round(float(vp.mean()),1),
            "var_sprint": round(float(vs.mean()),1),
            "efic":       round(float((g["pts_real"]/g["pts_prev"].replace(0,np.nan)).mean()),2),
            "estouro_pts": round(float((vp>0).mean()*100),0),
            "estouro_spr": round(float((vs>0).mean()*100),0),
            "duracao_med": round(float(g["duracao_dias"].mean()),0),
            "var_etapa":  var_et,
        }
    tend = {}
    if len(anos)>=2:
        a0,a1 = str(anos[0]),str(anos[-1])
        for k in ["var_pts","var_sprint","efic","estouro_pts"]:
            tend[k] = round(por_ano[a1][k]-por_ano[a0][k],2)
    return {"anos":[str(a) for a in anos], "por_ano":por_ano, "tendencia":tend}

"""## Baixar ferramenta para gráficos offline"""

def _baixar_chartjs() -> str:
    import urllib.request as _req
    for url in [
        "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js",
        "https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js",
    ]:
        try:
            with _req.urlopen(url, timeout=20) as r:
                js = r.read().decode("utf-8")
            print(f"   Chart.js: {len(js)//1024} KB embutido (offline).")
            return js
        except Exception as e:
            print(f"   [aviso] {e}")
    print("   [aviso] Chart.js não baixado — dashboard exige internet.")
    return ""

"""## Preparação dos dados para dashboard"""

def preparar_dados_dashboard(
    df, kpis, encoders,
    res_sprints, res_dias, res_plan,
    coef_sprints, coef_dias, coef_plan, coefs_dur_pre,
    motor_js=None, dados_anuais=None,
) -> dict:
    """
    Coleta e serializa todos os dados necessários para os gráficos
    e predições do dashboard HTML (Chart.js, sem Plotly).
    """
    import numpy as np

    ETAPAS_COLS = {
        "Est. Preliminar": "ep",
        "Anteprojeto":     "ap",
        "PE Arquitetura":  "pe_arq",
        "PE Engenharia":   "pe_eng",
        "Orçamento":       "orc",
    }

    # Recriar encodings no df se necessário
    for col in ("benfeitoria", "tipo_om", "tipo_obra"):
        enc = encoders.get(col)
        if enc and f"{col}_enc" not in df.columns:
            df[f"{col}_enc"] = enc.transform(df[col].fillna("desconhecido"))

    # Variância por etapa
    var_etapas = {}
    var_resumo = {}
    for nome, col in ETAPAS_COLS.items():
        v = df[f"var_{col}_pct"].dropna()
        var_etapas[nome] = v.round(1).tolist()
        q1, q3 = v.quantile(.25), v.quantile(.75)
        iqr = q3 - q1
        outliers = [
            {"id": int(df.loc[i, "id"]),
             "proj": df.loc[i, "projeto"][:28],
             "val": round(float(val), 1)}
            for i, val in v.items()
            if val > q3 + 1.5 * iqr or val < q1 - 1.5 * iqr
        ]
        var_resumo[nome] = {
            "media":    round(float(v.mean()), 1),
            "dp":       round(float(v.std()), 1),
            "mediana":  round(float(v.median()), 1),
            "pct_est":  round(float((v > 0).mean() * 100), 0),
            "outliers": outliers,
            "vals":     v.round(1).tolist(),
        }

    # Variância por projeto
    var_proj = {
        nome: df[f"var_{col}_pct"].fillna(0).round(1).tolist()
        for nome, col in ETAPAS_COLS.items()
    }
    projs = df["projeto"].str[:25].tolist()

    # Scatter
    scatter = {
        "pts": {
            "prev": df["pts_prev"].tolist(),
            "real": df["pts_real"].tolist(),
            "tipo": df["tipo_obra"].tolist(),
        },
        "sprint": {
            "prev": df["sprint_prev"].tolist(),
            "real": df["sprint_exec"].tolist(),
            "tipo": df["tipo_obra"].tolist(),
        },
    }

    # Eficiência e velocidade
    efic_obra = df.groupby("tipo_obra")["idx_eficiencia"].mean().round(3).to_dict()
    efic_n    = df.groupby("tipo_obra").size().to_dict()
    vel_df    = df[["projeto", "vel_prevista", "vel_realizada"]].dropna()
    vel_data  = {
        "ids":  vel_df["projeto"].str[:20].tolist(),
        "prev": vel_df["vel_prevista"].round(1).tolist(),
        "real": vel_df["vel_realizada"].round(1).tolist(),
    }

    # Tabela
    tabela = []
    for _, row in df.iterrows():
        real = row["pts_prev"]
        tabela.append({
            "id":          int(row["id"]),
            "projeto":     row["projeto"][:35],
            "tipo_obra":   row["tipo_obra"],
            "benfeitoria": row["benfeitoria"],
            "area":        round(float(row["area"]), 1) if pd.notna(row["area"]) else "—",
            "pts_prev":    real,
            "pts_real":    float(row["pts_real"]),
            "var_pts":     round((float(row["pts_real"]) - real) / real * 100, 1) if real else 0,
            "sprint_prev": int(row["sprint_prev"]) if pd.notna(row["sprint_prev"]) else 0,
            "sprint_exec": int(row["sprint_exec"]) if pd.notna(row["sprint_exec"]) else 0,
            "var_sprint":  round(
                (float(row["sprint_exec"]) - float(row["sprint_prev"]))
                / float(row["sprint_prev"]) * 100, 1
            ) if row["sprint_prev"] else 0,
            "duracao":     int(row["duracao_dias"]) if pd.notna(row["duracao_dias"]) else 0,
            "arq_reaprov": int(row[COL_ARQ_REAPROV]),
        })

    # Legenda projetos
    legenda_proj = [
        {"id": int(r["id"]), "projeto": r["projeto"],
         "tipo": r["tipo_obra"], "area": r["area"]}
        for r in tabela
    ]

    # Categorias e encodings para formulários
    cats = {
        "benfeitoria": sorted(df["benfeitoria"].dropna().unique().tolist()),
        "tipo_om":     sorted(df["tipo_om"].dropna().unique().tolist()),
        "tipo_obra":   sorted(df["tipo_obra"].dropna().unique().tolist()),
    }
    cats_enc = {}
    for cat, le in encoders.items():
        if cat == "feature_cols":
            continue
        cats_enc[cat] = {v: int(le.transform([v])[0]) for v in le.classes_}

    return {
        "kpis":           kpis,
        "var_etapas":     var_etapas,
        "var_resumo":     var_resumo,
        "var_proj":       var_proj,
        "projs":          projs,
        "scatter":        scatter,
        # Métricas: {modelo: {MAE, RMSE, R2}}
        "modelos_sprint": res_sprints,
        "modelos_dias":   res_dias,
        "modelos_plan":   res_plan,
        "efic_obra":      efic_obra,
        "efic_n":         efic_n,
        "vel":            vel_data,
        "tabela":         tabela,
        "legenda_proj":   legenda_proj,
        "cats":           cats,
        "cats_enc":       cats_enc,
        "coef_sprints":   coef_sprints,
        "coef_dias":      coef_dias,
        "coef_plan":      coef_plan,
        "coefs_dur_pre":  coefs_dur_pre,
        "motor":          motor_js or {},
        "anual":          dados_anuais or {},
    }

"""## Gerar relatório HTML"""

def gerar_html(dados: dict) -> str:
    """
    Gera dashboard HTML standalone usando Chart.js (cdnjs.cloudflare.com).
    Não requer Plotly nem nenhuma outra lib Python de visualização.
    Funciona offline após o carregamento inicial do CDN.
    """
    import json as _json

    K           = dados["kpis"]
    JS_DATA     = _json.dumps(dados, ensure_ascii=False, default=str)
    DA_DATA     = _json.dumps(dados.get("motor",{}), ensure_ascii=False, default=str)
    ANUAL_DATA  = _json.dumps(dados.get("anual",{}), ensure_ascii=False, default=str)
    CHARTJS      = _baixar_chartjs()
    cats      = dados["cats"]

    def opts(lista):
        return "".join(f'<option value="{v}">{v}</option>' for v in lista)

    opts_benf = opts(cats["benfeitoria"])
    opts_om   = opts(cats["tipo_om"])
    opts_obra = opts(cats["tipo_obra"])

    cor_pts  = "yellow" if abs(K["var_pts_media"])   > 20 else "green"
    cor_spr  = "yellow" if abs(K["var_sprint_media"]) > 20 else ""

    pior_card = ""
    if "pior_etapa" in K:
        pior_card = (
            f'<div class="kc"><div class="kl">Etapa Crítica</div>'
            f'<div class="kv" style="font-size:1.1rem">{K["pior_etapa"]}</div>'
            f'<div class="ks">var. média: {K["pior_etapa_var"]:+.1f}%</div></div>'
        )

    n = K["n_projetos"]

    # ── HTML ──────────────────────────────────────────────────────────────
    return f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Dashboard de projetos da CRO 5</title>
<link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;700;800&family=DM+Sans:wght@300;400;500&family=DM+Mono:wght@400;500&display=swap" rel="stylesheet">

<style>
:root{{--bg:#0d1117;--sf:#161b22;--br:#21262d;--tx:#e6edf3;--mu:#8b949e;
      --ac:#E8490F;--bl:#1B3A5C;--gr:#2E8B57;--ye:#F4C430;--rd:12px;
      --ff:'DM Sans',sans-serif;--fm:'DM Mono',monospace;--fd:'Syne',sans-serif}}
*,*::before,*::after{{box-sizing:border-box;margin:0;padding:0}}
html{{scroll-behavior:smooth}}
body{{background:var(--bg);color:var(--tx);font-family:var(--ff);font-size:15px;line-height:1.6}}
header{{background:linear-gradient(135deg,#0d1117 0%,#1B3A5C 100%);
  border-bottom:1px solid var(--br);padding:3rem 2rem 2rem;position:relative;overflow:hidden}}
header::before{{content:"";position:absolute;inset:0;
  background:radial-gradient(ellipse 60% 40% at 80% 50%,rgba(232,73,15,.12),transparent),
             radial-gradient(ellipse 40% 60% at 20% 50%,rgba(27,58,92,.4),transparent);
  pointer-events:none}}
.hi{{max-width:1200px;margin:auto;position:relative}}
h1{{font-family:var(--fd);font-size:clamp(1.8rem,4vw,3rem);font-weight:800;letter-spacing:-.02em;line-height:1.1}}
h1 span{{color:var(--ac)}} header p{{margin-top:.6rem;color:var(--mu);font-size:.95rem;font-weight:300}}
nav{{background:var(--sf);border-bottom:1px solid var(--br);position:sticky;top:0;z-index:100}}
.ni{{max-width:1200px;margin:auto;display:flex;gap:.25rem;overflow-x:auto;padding:0 1rem;scrollbar-width:none}}
.ni::-webkit-scrollbar{{display:none}}
.tb{{background:none;border:none;padding:.8rem 1.2rem;color:var(--mu);font-family:var(--ff);
    font-size:.875rem;font-weight:500;cursor:pointer;white-space:nowrap;
    border-bottom:2px solid transparent;transition:all .2s}}
.tb:hover{{color:var(--tx)}} .tb.active{{color:var(--ac);border-bottom-color:var(--ac)}}
main{{max-width:1200px;margin:0 auto;padding:2rem 1.5rem 4rem}}
.sec{{display:none}} .sec.active{{display:block;animation:fi .3s ease}}
@keyframes fi{{from{{opacity:0;transform:translateY(8px)}}to{{opacity:1;transform:none}}}}
.kg{{display:grid;grid-template-columns:repeat(auto-fill,minmax(165px,1fr));gap:1rem;margin-bottom:2rem}}
.kc{{background:var(--sf);border:1px solid var(--br);border-radius:var(--rd);
    padding:1.2rem 1rem;position:relative;overflow:hidden;transition:transform .2s,box-shadow .2s}}
.kc:hover{{transform:translateY(-2px);box-shadow:0 8px 24px rgba(0,0,0,.4)}}
.kc::after{{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--ac);border-radius:3px 0 0 3px}}
.kc.green::after{{background:var(--gr)}} .kc.yellow::after{{background:var(--ye)}}
.kl{{font-size:.75rem;text-transform:uppercase;letter-spacing:.08em;color:var(--mu);margin-bottom:.4rem}}
.kv{{font-family:var(--fd);font-size:2rem;font-weight:700;line-height:1}}
.ks{{font-size:.75rem;color:var(--mu);margin-top:.3rem}}
.cc{{background:var(--sf);border:1px solid var(--br);border-radius:var(--rd);padding:1.5rem;margin-bottom:1.5rem}}
.cr{{display:grid;grid-template-columns:1fr 1fr;gap:1.5rem}}
.cr3{{display:grid;grid-template-columns:3fr 2fr;gap:1.5rem}}
@media(max-width:720px){{.cr,.cr3{{grid-template-columns:1fr}}}}
.st{{font-family:var(--fd);font-size:1.4rem;font-weight:700;margin-bottom:1.5rem;
    padding-bottom:.5rem;border-bottom:1px solid var(--br)}}
.cht-wrap{{position:relative;width:100%}}
.tw{{overflow-x:auto;border-radius:var(--rd)}}
table{{width:100%;border-collapse:collapse;font-size:.8rem;font-family:var(--fm)}}
thead th{{background:var(--bl);padding:.6rem .8rem;text-align:left;font-weight:500;
         white-space:nowrap;position:sticky;top:0}}
tbody tr:nth-child(even){{background:rgba(255,255,255,.02)}}
tbody tr:hover{{background:rgba(232,73,15,.08)}}
tbody td{{padding:.5rem .8rem;border-bottom:1px solid var(--br)}}
.vp{{color:#ff6b6b}} .vn{{color:var(--gr)}} .vm{{color:var(--mu)}}
.badge{{display:inline-block;padding:2px 8px;border-radius:20px;font-size:.7rem;font-weight:500}}
.leg-grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:.5rem;margin-top:1.5rem}}
.leg-item{{display:flex;align-items:center;gap:.6rem;padding:.4rem .6rem;
          border-radius:6px;background:rgba(255,255,255,.03);border:1px solid var(--br);font-size:.82rem}}
.leg-id{{font-family:var(--fm);font-weight:700;min-width:24px;text-align:center;
        padding:2px 6px;border-radius:4px;font-size:.75rem}}
.cht-legend{{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:8px;font-size:12px;color:var(--mu)}}
.cht-legend span{{display:flex;align-items:center;gap:5px}}
.cht-legend i{{width:10px;height:10px;border-radius:2px;flex-shrink:0}}
.var-resumo{{background:var(--bg);border-radius:8px;padding:1rem}}
.ve{{border-bottom:1px solid var(--br);padding:.7rem 0}} .ve:last-child{{border-bottom:none}}
.ve-nome{{font-size:.8rem;font-weight:500;color:var(--tx);margin-bottom:.3rem;
         text-transform:uppercase;letter-spacing:.05em}}
.ve-stats{{display:flex;gap:.8rem;font-size:.78rem;color:var(--mu);margin-bottom:.3rem}}
.out-item{{display:inline-flex;align-items:center;gap:.3rem;padding:2px 6px;
          border-radius:4px;margin:.2rem .2rem 0 0;border:1px solid;font-size:.73rem}}
.pf{{background:var(--sf);border:1px solid var(--br);border-radius:var(--rd);padding:2rem}}
.pf .hint{{color:var(--mu);font-size:.85rem;margin-bottom:1.5rem;line-height:1.6}}
.fg{{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:1rem;margin-bottom:1.5rem}}
.fg.sm{{max-width:700px}}
.fl{{display:block;font-size:.75rem;text-transform:uppercase;letter-spacing:.06em;color:var(--mu);margin-bottom:.4rem}}
.fi input,.fi select{{width:100%;background:var(--bg);border:1px solid var(--br);
  border-radius:8px;padding:.6rem .8rem;color:var(--tx);font-family:var(--fm);
  font-size:.85rem;transition:border-color .2s}}
.fi input:focus,.fi select:focus{{outline:none;border-color:var(--ac)}}
.fi select option{{background:var(--sf)}}
.cbr{{display:flex;align-items:center;gap:.6rem;padding:.4rem 0;margin-bottom:1rem}}
.cbr input[type=checkbox]{{width:18px;height:18px;accent-color:var(--ac);cursor:pointer}}
.cbr label{{font-size:.85rem;cursor:pointer;color:var(--tx)}}
.bp{{background:var(--ac);color:#fff;border:none;border-radius:8px;padding:.8rem 2rem;
    font-family:var(--fd);font-size:1rem;font-weight:700;cursor:pointer;
    transition:opacity .2s,transform .2s;letter-spacing:.04em}}
.bp:hover{{opacity:.9;transform:translateY(-1px)}}
.pr{{margin-top:1.5rem;padding:1.5rem;background:var(--bg);border:1px solid var(--br);
    border-radius:var(--rd);display:none}}
.pr.show{{display:grid;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:1rem}}
.pi{{text-align:center}}
.pn{{font-family:var(--fd);font-size:2.2rem;font-weight:800;color:var(--ac)}}
.pm{{font-size:.75rem;color:var(--mu);margin-top:.25rem}}
.pnote{{grid-column:1/-1;font-size:.75rem;color:var(--mu);
       border-top:1px solid var(--br);padding-top:.75rem;margin-top:.5rem}}
.infobox{{background:rgba(232,73,15,.08);border:1px solid rgba(232,73,15,.3);
         border-radius:8px;padding:.8rem 1rem;font-size:.82rem;color:var(--mu);
         line-height:1.6;margin-bottom:1rem}}
.infobox strong{{color:var(--tx)}}
.mbtn{{background:var(--sf);border:1px solid var(--br);border-radius:6px;padding:.4rem .9rem;
    color:var(--mu);font-family:var(--ff);font-size:.8rem;font-weight:500;cursor:pointer;transition:all .2s}}
.mbtn:hover{{color:var(--tx);border-color:var(--mu)}}
.mbtn.active{{background:var(--ac);border-color:var(--ac);color:#fff}}
</style>
</head>
<body>
<header><div class="hi">
  <h1>Análise de Projetos da <span>CRO 5</span></h1>
  <p>Metodologia SCRUM · Banco de dados: {n} projetos</p>
</div></header>
<nav><div class="ni">
  <button class="tb active" onclick="setTab('hist',this)">📊 Análise Histórica</button>




  <button class="tb" onclick="setTab('plan',this)">🎯 Planejar Projeto</button>
  <button class="tb" onclick="setTab('dad',this)">📋 Dados</button>
</div></nav>
<main>

<div class="sec active" id="hist">
  <p class="st">Visão Geral</p>
  <div class="kg">
    <div class="kc"><div class="kl">Projetos</div>
      <div class="kv">{n}</div><div class="ks">com dados completos</div></div>
    <div class="kc {cor_pts}"><div class="kl">Var. média — pontos</div>
      <div class="kv">{K["var_pts_media"]:+.1f}%</div>
      <div class="ks">{K["pct_estourou_pontos"]:.0f}% estouraram</div></div>
    <div class="kc {cor_spr}"><div class="kl">Var. média — sprints</div>
      <div class="kv">{K["var_sprint_media"]:+.1f}%</div>
      <div class="ks">{K["pct_estourou_sprint"]:.0f}% estouraram</div></div>
    <div class="kc green"><div class="kl">Índice eficiência</div>
      <div class="kv">{K["idx_efic_media"]:.2f}</div><div class="ks">exec/prev (1 = perfeito)</div></div>
    <div class="kc"><div class="kl">Duração média</div>
      <div class="kv">{K["duracao_media"]:.0f}</div><div class="ks">dias por projeto</div></div>
    {pior_card}
  </div>
  <div class="cc"><div class="cht-legend" id="leg-scat-pts"></div>
    <div class="cht-wrap"><canvas id="ch-scat-pts" role="img"
      aria-label="Dispersão pontos previstos versus realizados"></canvas></div></div>
  <div class="cc"><div class="cht-legend" id="leg-scat-spr"></div>
    <div class="cht-wrap"><canvas id="ch-scat-spr" role="img"
      aria-label="Dispersão sprints previstos versus executados"></canvas></div></div>
  <div class="cc">
    <div style="font-size:.8rem;font-weight:500;text-transform:uppercase;letter-spacing:.06em;color:var(--mu);margin-bottom:.8rem">Legenda dos Projetos</div>
    <div class="leg-grid" id="legenda-proj"></div>
  </div>
</div>

<div class="sec" id="var">
  <p class="st">Variância por Etapa</p>
  <div class="cr3">
    <div class="cc"><div class="cht-legend" id="leg-var"></div>
      <div class="cht-wrap"><canvas id="ch-var-pts" style="max-height:380px" role="img"
        aria-label="Variação percentual por etapa"></canvas></div></div>
    <div class="cc" style="padding:1rem">
      <div style="font-size:.8rem;font-weight:500;text-transform:uppercase;letter-spacing:.06em;color:var(--mu);margin-bottom:.8rem">Resumo por etapa</div>
      <div class="var-resumo" id="var-resumo-panel"></div>
    </div>
  </div>
  <div class="cc"><div class="cht-wrap"><canvas id="ch-var-proj" style="max-height:420px" role="img"
    aria-label="Variação por projeto e etapa"></canvas></div></div>
</div>

<div class="sec" id="efi">
  <p class="st">Eficiência por Categoria</p>
  <div class="cc"><div class="cht-legend" id="leg-efic"></div>
    <div class="cht-wrap"><canvas id="ch-efic" style="max-height:300px" role="img"
      aria-label="Índice de eficiência por tipo de obra"></canvas></div></div>
  <div class="cc"><div class="cht-wrap"><canvas id="ch-vel" style="max-height:340px" role="img"
    aria-label="Velocidade de sprint prevista versus realizada"></canvas></div></div>
</div>

<div class="sec" id="mod">
  <p class="st">Comparação de Modelos (LOO-CV)</p>
  <div class="cc" style="padding:1rem 1.5rem">
    <div style="display:flex;align-items:center;gap:1.5rem;flex-wrap:wrap">
      <span style="font-size:.8rem;text-transform:uppercase;letter-spacing:.06em;color:var(--mu)">Métrica:</span>
      <div style="display:flex;gap:.5rem" id="metric-btns">
        <button class="mbtn active" onclick="setMetrica('MAE',this)">MAE</button>
        <button class="mbtn" onclick="setMetrica('RMSE',this)">RMSE</button>
        <button class="mbtn" onclick="setMetrica('R2',this)">R²</button>
      </div>
      <span id="metric-hint" style="font-size:.78rem;color:var(--mu);flex:1;min-width:200px"></span>
    </div>
  </div>
  <div class="cc"><div style="font-size:.8rem;color:var(--mu);margin-bottom:.5rem">Predição de Sprints</div>
    <div class="cht-wrap"><canvas id="ch-mod-spr" style="max-height:260px" role="img"
      aria-label="Comparação de modelos para sprints"></canvas></div></div>
  <div class="cr">
    <div class="cc"><div style="font-size:.8rem;color:var(--mu);margin-bottom:.5rem">Predição de Dias</div>
      <div class="cht-wrap"><canvas id="ch-mod-dia" style="max-height:260px" role="img"
        aria-label="Comparação de modelos para dias"></canvas></div></div>
    <div class="cc"><div style="font-size:.8rem;color:var(--mu);margin-bottom:.5rem">Planejamento — média por etapa</div>
      <div class="cht-wrap"><canvas id="ch-mod-pln" style="max-height:260px" role="img"
        aria-label="Comparação de modelos para planejamento"></canvas></div></div>
  </div>
  <div class="cc">
    <div style="font-size:.8rem;font-weight:500;text-transform:uppercase;letter-spacing:.06em;color:var(--mu);margin-bottom:.8rem">Resumo de Métricas</div>
    <div class="tw"><table id="tab-mod"><thead></thead><tbody></tbody></table></div>
  </div>
  <div class="cc" style="padding:1.5rem">
    <p style="color:var(--mu);font-size:.85rem;line-height:1.7">
      <strong style="color:var(--tx)">MAE</strong> — erro médio em unidades originais. Robusto a outliers.<br>
      <strong style="color:var(--tx)">RMSE</strong> — penaliza erros grandes quadraticamente. Útil quando grandes desvios são críticos.<br>
      <strong style="color:var(--tx)">R²</strong> — fração da variância explicada pelo modelo. Com LOO-CV e n={n}, valores negativos
      indicam que o modelo performa pior que prever a média — informação relevante para a discussão.<br><br>
      <strong style="color:var(--tx)">LOO-CV</strong> — com {n} projetos, cada modelo treina com n−1 amostras e testa na restante.
    </p>
  </div>
</div>

<div class="sec" id="pred">
  <p class="st">Predição do Projeto</p>
  <div class="pf">
    <p class="hint">Preencha as características do novo projeto para obter a
      <strong style="color:var(--tx)">estimativa de duração</strong> e a
      <strong style="color:var(--tx)">distribuição de pontos por etapa</strong> simultaneamente.</p>
    <div class="infobox">
      <strong>Modelo pré-projeto</strong> — usa apenas o que se sabe antes de começar:
      área · benfeitoria · tipo de OM · tipo de obra · arq_reaprov.<br>
      Duração: Ridge LOO-CV MAE ≈ 6,3 sprints · 88 dias &nbsp;|&nbsp;
      Pontos: Lasso LOO-CV MAE médio ≈ 38,5 pts/etapa.
    </div>
    <div class="fg sm">
      <div class="fi"><label class="fl">Área construída (m²)</label>
        <input type="number" id="f_area" placeholder="ex: 500" min="0"></div>
      <div class="fi"><label class="fl">Tipo de benfeitoria</label>
        <select id="f_benf"><option value="desconhecido">-- selecione --</option>{opts_benf}</select></div>
      <div class="fi"><label class="fl">Tipo de OM</label>
        <select id="f_om"><option value="desconhecido">-- selecione --</option>{opts_om}</select></div>
      <div class="fi"><label class="fl">Tipo de obra</label>
        <select id="f_obra"><option value="desconhecido">-- selecione --</option>{opts_obra}</select></div>
    </div>
    <div class="cbr"><input type="checkbox" id="f_reaprov">
      <label for="f_reaprov">Arquitetura reaproveitada de outro projeto
        <span style="font-size:.75rem;color:var(--mu)"> — desconto de ~−174 pts (1 projeto; refina com mais dados)</span>
      </label></div>
    <button class="bp" onclick="calcularPredicao()">Calcular Estimativas</button>
    <div id="pred-res" style="display:none">
      <div style="margin-top:1.5rem;padding-bottom:.6rem;border-bottom:1px solid var(--br)">
        <span style="font-size:.75rem;text-transform:uppercase;letter-spacing:.08em;color:var(--mu)">Duração estimada</span>
      </div>
      <div class="pr show" style="margin-top:.75rem">
        <div class="pi"><div class="pn" id="f-spr">—</div><div class="pm">Sprints</div></div>
        <div class="pi"><div class="pn" id="f-dia">—</div><div class="pm">Dias</div></div>
        <div class="pnote">Ridge · LOO-CV MAE ≈ 6,3 sprints · 88 dias</div>
      </div>
      <div style="margin-top:1.5rem;padding-bottom:.6rem;border-bottom:1px solid var(--br)">
        <span style="font-size:.75rem;text-transform:uppercase;letter-spacing:.08em;color:var(--mu)">Distribuição de pontos sugerida</span>
      </div>
      <div class="pr show" style="margin-top:.75rem">
        <div class="pi"><div class="pn" id="f-tot" style="color:var(--ac)">—</div><div class="pm">Total</div></div>
        <div class="pi"><div class="pn" id="f-ep"  style="font-size:1.6rem;color:#3A7CA5">—</div><div class="pm">EP</div></div>
        <div class="pi"><div class="pn" id="f-ap"  style="font-size:1.6rem;color:#3A7CA5">—</div><div class="pm">AP</div></div>
        <div class="pi"><div class="pn" id="f-pe-arq" style="font-size:1.6rem;color:#3A7CA5">—</div><div class="pm">PE Arq</div></div>
        <div class="pi"><div class="pn" id="f-pe-eng" style="font-size:1.6rem;color:#3A7CA5">—</div><div class="pm">PE Eng</div></div>
        <div class="pi"><div class="pn" id="f-orc" style="font-size:1.6rem;color:#3A7CA5">—</div><div class="pm">Orçamento</div></div>
        <div class="pnote">Lasso · LOO-CV MAE médio = 38,5 pts/etapa</div>
      </div>
      <div style="margin-top:1.5rem">
        <div class="cht-legend" id="leg-pie"></div>
        <div class="cht-wrap"><canvas id="pred-pie" style="max-height:280px" role="img"
          aria-label="Distribuição de pontos por etapa"></canvas></div>
      </div>
    </div>
  </div>
</div>

<div class="sec" id="dad">
  <p class="st">Dados dos Projetos</p>
  <div class="cc"><div class="tw">
    <table id="tab-p"><thead></thead><tbody></tbody></table>
  </div></div>

      <!-- ── Análise Anual ── -->
      <div style="margin-top:2rem">
        <p class="st" style="font-size:1rem;margin-bottom:1rem">Evolução Anual do Portfólio</p>
        <div id="anual-body"></div>
        <div class="cr" style="margin-top:1.25rem">
          <div class="cc">
            <p style="font-size:.8rem;color:var(--mu);margin-bottom:.5rem">Variância média por etapa — por ano</p>
            <div class="cht-wrap"><canvas id="ch-anual" style="max-height:260px"></canvas></div>
          </div>
          <div class="cc">
            <p style="font-size:.8rem;color:var(--mu);margin-bottom:.5rem">Tendências entre o primeiro e último ano</p>
            <div id="tend-resumo" style="font-size:.83rem"></div>
          </div>
        </div>
      </div>
</div>

</main>


  <!-- ════ PLANEJAR PROJETO ════ -->
  <div class="sec" id="plan">
    <p class="st">Planejar Novo Projeto</p>
    <div class="infobox">
      Preencha as informações disponíveis antes do início do projeto.
      O sistema estima o esforço por fase, o prazo e a curva de entrega usando
      modelos treinados com os <strong>{n} projetos históricos</strong> do portfólio.
    </div>
    <div class="cr">
      <!-- Formulário -->
      <div class="cc" style="min-width:280px;max-width:380px">
        <p class="st" style="font-size:.95rem;margin-bottom:1rem">Dados do Projeto</p>
        <div class="fg">
          <div class="fi"><label class="fl">Tipo de obra</label>
            <select id="pl_obra" onchange="plAtualizarAP()"><option value="">-- selecione --</option></select></div>
          <div class="fi"><label class="fl">Tipo de benfeitoria</label>
            <select id="pl_benf"><option value="">-- selecione --</option></select></div>
          <div class="fi"><label class="fl">Tipo de OM</label>
            <select id="pl_om"><option value="">-- selecione --</option></select></div>
          <div class="fi"><label class="fl">Área construída (m²)</label>
            <input type="number" id="pl_area" placeholder="ex: 500" min="0"></div>
          <div class="fi">
            <label class="fl">Qtd. disciplinas de engenharia no PE</label>
            <div style="display:grid;grid-template-columns:auto 1fr;align-items:center;gap:.75rem;margin-bottom:.5rem">
              <select id="pl_n_disc" style="width:70px">
                <option value="1">1</option><option value="2">2</option><option value="3">3</option>
                <option value="4">4</option><option value="5">5</option><option value="6" selected>6</option>
                <option value="7">7</option><option value="8">8</option>
              </select>
              <div style="font-size:.72rem;color:var(--mu);line-height:1.5">
                Conte as disciplinas presentes:<br>
                <strong>EST</strong> Estrutural · <strong>FUND</strong> Fundações ·
                <strong>COB</strong> Cobertura · <strong>ELE</strong> Elétrica ·
                <strong>HIDRO</strong> Hidrossanitário · <strong>MEC</strong> Mecânica ·
                <strong>PPCI/PSCIP</strong> Incêndio · <strong>INFRA/SUPRA</strong> Infraestrutura
              </div>
            </div>
          </div>
        </div>
        <div class="cbr"><input type="checkbox" id="pl_reaprov">
          <label for="pl_reaprov">Arquitetura reaproveitada de outro projeto</label></div>
        <div id="pl-ap-info" style="margin:.5rem 0"></div>
        <button class="bp" style="width:100%;margin-top:1rem" onclick="calcularPlano()">
          Calcular Estimativas
        </button>
      </div>
      <!-- Resultado -->
      <div id="pl-resultado" style="display:none;flex:1;min-width:0">
        <p class="st" style="font-size:.95rem;margin-bottom:.75rem">Estimativa de Esforço por Fase</p>
        <!-- Semáforo de confiança -->
        <div style="display:flex;flex-wrap:wrap;gap:.4rem;margin-bottom:1rem" id="pl-semaforo"></div>
        <!-- Grid de pontos -->
        <div id="pl-pts-grid" class="pr show" style="margin-bottom:1.25rem"></div>
        <p class="st" style="font-size:.95rem;margin-bottom:.75rem">Estimativa de Prazo</p>
        <div id="pl-prazo-grid" class="pr show" style="margin-bottom:1.25rem"></div>
        <p class="st" style="font-size:.95rem;margin-bottom:.75rem">Perfil de Entrega (Curva S)</p>
        <div class="cht-legend" id="leg-pl-sc"></div>
        <div class="cht-wrap"><canvas id="ch-pl-sc" style="max-height:260px"></canvas></div>
        <div id="pl-alertas" style="margin-top:1.25rem"></div>
        <p class="st" style="font-size:.95rem;margin:.75rem 0 .5rem">Projetos Análogos</p>
        <div id="pl-similares"></div>
      </div>
    </div>
  </div>

<script>{CHARTJS}</script>


<script>

const D = {JS_DATA};
  const DA = {DA_DATA};
  const ANUAL = {ANUAL_DATA};
const CORES_OBRA = {{'Adequação - Tipo 1':'#E8490F','Adequação - Tipo 2':'#F4C430',
  'Construção':'#1B3A5C','Reforma':'#2E8B57'}};
const PAL = ['#1B3A5C','#E8490F','#2E8B57','#F4C430','#6C757D','#8B1A4A','#3A7CA5','#FF8C00'];
Chart.defaults.color = '#8b949e';
Chart.defaults.font.family = 'DM Sans, sans-serif';
Chart.defaults.font.size = 12;
const GR = 'rgba(255,255,255,.07)', ZR = 'rgba(255,255,255,.18)';
const BO = {{
  responsive:true, maintainAspectRatio:true,
  plugins:{{legend:{{display:false}}}},
  scales:{{
    x:{{grid:{{color:GR}},border:{{display:false}},ticks:{{color:'#8b949e'}}}},
    y:{{grid:{{color:GR}},border:{{display:false}},ticks:{{color:'#8b949e'}}}}
  }}
}};
function mkLegend(id, items) {{
  const el = document.getElementById(id);
  if (el) el.innerHTML = items.map(([l,c]) => `<span><i style="background:${{c}}"></i>${{l}}</span>`).join('');
}}
function setTab(id, btn) {{
  document.querySelectorAll('.sec').forEach(s => s.classList.remove('active'));
  document.querySelectorAll('.tb').forEach(b => b.classList.remove('active'));
  document.getElementById(id).classList.add('active');
  btn.classList.add('active');
}}
const ID_LBL = {{
  id:'idLabels',
  afterDatasetsDraw(chart) {{
    const {{ctx:c}} = chart;
    const meta = chart.getDatasetMeta(0);
    if (!meta) return;
    c.save(); c.font='bold 11px DM Mono,monospace'; c.fillStyle='#e6edf3'; c.textAlign='center';
    meta.data.forEach((pt,i) => {{ c.fillText('P'+D.legenda_proj[i].id, pt.x, pt.y-10); }});
    c.restore();
  }}
}};
const VLINE = {{
  id:'vline',
  afterDraw(chart) {{
    const {{ctx:c,chartArea:a,scales:{{x}}}} = chart;
    if (!x) return;
    const xp = x.getPixelForValue(1);
    c.save(); c.strokeStyle='rgba(255,255,255,.3)'; c.setLineDash([5,4]); c.lineWidth=1.5;
    c.beginPath(); c.moveTo(xp,a.top); c.lineTo(xp,a.bottom); c.stroke(); c.restore();
  }}
}};
// scatter pontos
(function(){{
  const s=D.scatter.pts, mn=Math.min(...s.prev,...s.real)-20, mx=Math.max(...s.prev,...s.real)+20;
  new Chart(document.getElementById('ch-scat-pts').getContext('2d'),{{
    type:'scatter',
    data:{{datasets:[
      {{label:'Projetos',data:s.prev.map((x,i)=>({{x,y:s.real[i]}})),
        backgroundColor:s.tipo.map(t=>(CORES_OBRA[t]||'#888')+'cc'),
        borderColor:s.tipo.map(t=>CORES_OBRA[t]||'#888'),
        borderWidth:1,pointRadius:9,pointHoverRadius:12}},
      {{type:'line',data:[{{x:mn,y:mn}},{{x:mx,y:mx}}],
        borderColor:'rgba(255,255,255,.25)',borderDash:[5,4],borderWidth:1.5,pointRadius:0,fill:false}}
    ]}},
    options:{{...BO,aspectRatio:1.8,
      plugins:{{legend:{{display:false}},tooltip:{{callbacks:{{label:c2=>
        `P${{D.legenda_proj[c2.dataIndex].id}} — ${{D.legenda_proj[c2.dataIndex].projeto}} | Prev:${{s.prev[c2.dataIndex]}} Real:${{s.real[c2.dataIndex]}}`
      }}}}}},
      scales:{{x:{{...BO.scales.x,title:{{display:true,text:'Previsto (pts)',color:'#8b949e'}}}},
               y:{{...BO.scales.y,title:{{display:true,text:'Realizado (pts)',color:'#8b949e'}}}}}}}},
    plugins:[ID_LBL]
  }});
  mkLegend('leg-scat-pts',[...new Set(s.tipo)].sort().map(t=>[t,CORES_OBRA[t]||'#888']));
}})();
// scatter sprints
(function(){{
  const s=D.scatter.sprint, mn=Math.min(...s.prev,...s.real)-1, mx=Math.max(...s.prev,...s.real)+1;
  new Chart(document.getElementById('ch-scat-spr').getContext('2d'),{{
    type:'scatter',
    data:{{datasets:[
      {{data:s.prev.map((x,i)=>({{x,y:s.real[i]}})),
        backgroundColor:s.tipo.map(t=>(CORES_OBRA[t]||'#888')+'cc'),
        borderColor:s.tipo.map(t=>CORES_OBRA[t]||'#888'),
        borderWidth:1,pointRadius:9,pointHoverRadius:12}},
      {{type:'line',data:[{{x:mn,y:mn}},{{x:mx,y:mx}}],
        borderColor:'rgba(255,255,255,.25)',borderDash:[5,4],borderWidth:1.5,pointRadius:0,fill:false}}
    ]}},
    options:{{...BO,aspectRatio:2.2,
      plugins:{{legend:{{display:false}},tooltip:{{callbacks:{{label:c2=>
        `P${{D.legenda_proj[c2.dataIndex].id}} — ${{D.legenda_proj[c2.dataIndex].projeto}} | Prev:${{s.prev[c2.dataIndex]}} Exec:${{s.real[c2.dataIndex]}}`
      }}}}}},
      scales:{{x:{{...BO.scales.x,title:{{display:true,text:'Previsto (sprints)',color:'#8b949e'}}}},
               y:{{...BO.scales.y,title:{{display:true,text:'Executado (sprints)',color:'#8b949e'}}}}}}}},
    plugins:[ID_LBL]
  }});
  mkLegend('leg-scat-spr',[...new Set(s.tipo)].sort().map(t=>[t,CORES_OBRA[t]||'#888']));
}})();
// legenda projetos
(function(){{
  const el=document.getElementById('legenda-proj');
  D.legenda_proj.forEach(p=>{{
    const cor=CORES_OBRA[p.tipo]||'#888', div=document.createElement('div');
    div.className='leg-item';
    div.innerHTML=`<span class="leg-id" style="background:${{cor}}25;color:${{cor}};border:1px solid ${{cor}}50">P${{p.id}}</span>
      <span style="flex:1;color:var(--tx)">${{p.projeto}}</span>
      <span class="badge" style="background:${{cor}}20;color:${{cor}};border:1px solid ${{cor}}35">${{p.tipo}}</span>`;
    el.appendChild(div);
  }});
}})();
// variância boxplot simplificado (barra média + pontos individuais)
(function(){{
  const etapas=Object.keys(D.var_etapas);
  const medias=etapas.map(e=>D.var_resumo[e]?D.var_resumo[e].media:0);
  new Chart(document.getElementById('ch-var-pts').getContext('2d'),{{
    type:'bar',
    data:{{labels:etapas,datasets:[
      {{label:'Média',data:medias,
        backgroundColor:medias.map(v=>v>0?'#E8490F88':'#2E8B5788'),
        borderColor:medias.map(v=>v>0?'#E8490F':'#2E8B57'),
        borderWidth:1.5,borderRadius:4}},
      ...etapas.map((e,i)=>({{type:'scatter',label:e,
        data:(D.var_etapas[e]||[]).map(v=>({{x:e,y:v}})),
        backgroundColor:PAL[i]+'cc',borderColor:PAL[i],pointRadius:6,pointHoverRadius:8,showLine:false}}))
    ]}},
    options:{{...BO,aspectRatio:1.6,
      plugins:{{legend:{{display:false}},tooltip:{{mode:'index',intersect:false}}}},
      scales:{{x:{{...BO.scales.x}},
               y:{{...BO.scales.y,title:{{display:true,text:'Variação %',color:'#8b949e'}},
                  grid:{{color:ctx=>ctx.tick.value===0?ZR:GR}}}}}}}}
  }});
  mkLegend('leg-var',[['Positivo = estourou','#E8490F'],['Negativo = ficou abaixo','#2E8B57']]);
  // resumo
  const panel=document.getElementById('var-resumo-panel');
  Object.entries(D.var_resumo).forEach(([nome,r])=>{{
    const outHtml=r.outliers.map(o=>{{
      const cor=o.val>0?'#ff6b6b':'#2E8B57', bdr=o.val>0?'rgba(255,107,107,.4)':'rgba(46,139,87,.4)';
      return `<span class="out-item" style="color:${{cor}};border-color:${{bdr}};background:${{cor}}15">P${{o.id}} ${{o.val>0?'+':''}}${{o.val}}%</span>`;
    }}).join('');
    panel.innerHTML+=`<div class="ve"><div class="ve-nome">${{nome}}</div>
      <div class="ve-stats">
        <span>média <b style="color:${{r.media>0?'#ff6b6b':'#2E8B57'}}">${{r.media>0?'+':''}}${{r.media}}%</b></span>
        <span>dp <b>${{r.dp}}%</b></span><span>estourou <b>${{r.pct_est}}%</b></span>
      </div>
      ${{r.outliers.length?`<div style="margin-top:.3rem;font-size:.72rem;color:var(--mu)">Outliers IQR:</div><div>${{outHtml}}</div>`:''}}</div>`;
  }});
}})();
// variância por projeto
(function(){{
  new Chart(document.getElementById('ch-var-proj').getContext('2d'),{{
    type:'bar',
    data:{{labels:D.projs,datasets:Object.entries(D.var_proj).map(([e,vals],i)=>{{return{{
      label:e,data:vals,backgroundColor:PAL[i]+'bb',borderColor:PAL[i],borderWidth:1,borderRadius:2}};}})}},
    options:{{...BO,aspectRatio:1.8,
      plugins:{{legend:{{display:true,position:'top',labels:{{color:'#8b949e',boxWidth:10,padding:14}}}}}},
      scales:{{x:{{...BO.scales.x,ticks:{{color:'#8b949e',maxRotation:40}}}},
               y:{{...BO.scales.y,title:{{display:true,text:'Variação %',color:'#8b949e'}},
                  grid:{{color:ctx=>ctx.tick.value===0?ZR:GR}}}}}}}}
  }});
}})();
// eficiência
(function(){{
  const tipos=Object.keys(D.efic_obra), vals=tipos.map(t=>+D.efic_obra[t].toFixed(3));
  new Chart(document.getElementById('ch-efic').getContext('2d'),{{
    type:'bar',
    data:{{labels:tipos,datasets:[{{data:vals,
      backgroundColor:vals.map(v=>v>1?'#E8490F99':'#2E8B5799'),
      borderColor:vals.map(v=>v>1?'#E8490F':'#2E8B57'),
      borderWidth:1.5,borderRadius:4}}]}},
    options:{{...BO,indexAxis:'y',aspectRatio:2.5,
      plugins:{{legend:{{display:false}},tooltip:{{callbacks:{{label:c=>
        ` ${{c.raw.toFixed(3)}} (n=${{D.efic_n[c.label]}}) — ${{c.raw>1?'estourou':'dentro do planejamento'}}`
      }}}}}},
      scales:{{x:{{...BO.scales.x,title:{{display:true,text:'Exec/Prev (1 = planejamento exato)',color:'#8b949e'}},
               grid:{{color:ctx=>ctx.tick.value===1?ZR:GR}}}},y:{{...BO.scales.y}}}}}},
    plugins:[VLINE]
  }});
  mkLegend('leg-efic',[['> 1 — estourou','#E8490F'],['≤ 1 — dentro do planejamento','#2E8B57']]);
}})();
// velocidade sprint
(function(){{
  const v=D.vel;
  new Chart(document.getElementById('ch-vel').getContext('2d'),{{
    type:'bar',
    data:{{labels:v.ids,datasets:[
      {{label:'Prevista', data:v.prev,backgroundColor:'#1B3A5Ccc',borderColor:'#1B3A5C',borderWidth:1.5,borderRadius:3}},
      {{label:'Realizada',data:v.real,backgroundColor:'#E8490Fcc',borderColor:'#E8490F',borderWidth:1.5,borderRadius:3}}
    ]}},
    options:{{...BO,aspectRatio:2,
      plugins:{{legend:{{display:true,position:'right',labels:{{color:'#8b949e',boxWidth:10}}}}}},
      scales:{{x:{{...BO.scales.x,ticks:{{color:'#8b949e',maxRotation:40}}}},
               y:{{...BO.scales.y,title:{{display:true,text:'Pts/sprint',color:'#8b949e'}}}}}}}}
  }});
}})();
// ── modelos com seletor dinâmico de métrica ──────────────────────────────
const METRIC_HINTS = {{
  MAE:  'Erro médio absoluto — unidades originais. Robusto a outliers.',
  RMSE: 'Raiz do erro quadrático médio — penaliza erros grandes.',
  R2:   'R² LOO-CV — fração da variância explicada. Valores negativos indicam modelo pior que a média.',
}};
const METRIC_LABEL = {{
  MAE:'MAE (unidade original)', RMSE:'RMSE (unidade original)', R2:'R² (adimensional, melhor = 1)'
}};
let metricaAtual = 'MAE';
const modCharts = {{}};

function getMetricaVals(dados, metrica) {{
  return Object.entries(dados).map(([,v]) =>
    typeof v === 'object' ? (v[metrica] ?? 0) : v
  );
}}

function buildModChart(elId, dados, ratio, metrica) {{
  const ns   = Object.keys(dados);
  const vals = getMetricaVals(dados, metrica);
  // Para R²: maior é melhor; para MAE/RMSE: menor é melhor
  const isR2 = metrica === 'R2';
  const bestIdx = isR2
    ? vals.indexOf(Math.max(...vals))
    : vals.indexOf(Math.min(...vals));
  const ctx = document.getElementById(elId).getContext('2d');
  const chart = new Chart(ctx, {{
    type: 'bar',
    data: {{
      labels: ns,
      datasets: [{{
        data: vals,
        backgroundColor: ns.map((_,i) => i===bestIdx ? '#2E8B5799' : '#1B3A5C99'),
        borderColor:     ns.map((_,i) => i===bestIdx ? '#2E8B57'   : '#1B3A5C'),
        borderWidth: 1.5, borderRadius: 3
      }}]
    }},
    options: {{
      ...BO, indexAxis:'y', aspectRatio: ratio||1.8,
      plugins: {{
        legend: {{display:false}},
        tooltip: {{callbacks: {{label: c => ` ${{metrica}} = ${{c.raw}}`}}}}
      }},
      scales: {{
        x: {{...BO.scales.x, title:{{display:true, text:METRIC_LABEL[metrica], color:'#8b949e'}},
             grid:{{color: ctx2 => (isR2 && ctx2.tick.value===0) ? ZR : GR}}}},
        y: {{...BO.scales.y}}
      }}
    }}
  }});
  return chart;
}}

function setMetrica(metrica, btn) {{
  metricaAtual = metrica;
  document.querySelectorAll('.mbtn').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
  const hint = document.getElementById('metric-hint');
  if (hint) hint.textContent = METRIC_HINTS[metrica] || '';
  // Atualizar os 3 gráficos
  [['ch-mod-spr', D.modelos_sprint, 2.2],
   ['ch-mod-dia', D.modelos_dias,   1.8],
   ['ch-mod-pln', D.modelos_plan,   1.6]].forEach(([id, dados, ratio]) => {{
    if (modCharts[id]) modCharts[id].destroy();
    modCharts[id] = buildModChart(id, dados, ratio, metrica);
  }});
  // Atualizar tabela
  buildTabMod(metrica);
}}

function buildTabMod(metrica) {{
  const metricas = ['MAE','RMSE','R2'];
  const alvos    = [
    ['Sprints',     D.modelos_sprint],
    ['Dias',        D.modelos_dias],
    ['Planejamento',D.modelos_plan],
  ];
  const thead = document.querySelector('#tab-mod thead');
  const tbody = document.querySelector('#tab-mod tbody');
  if (!thead || !tbody) return;
  thead.innerHTML = '<tr><th>Modelo</th>' +
    alvos.map(([a]) => metricas.map(m =>
      `<th style="${{m===metrica?'color:var(--ac)':''}}">${{a}} ${{m}}</th>`
    ).join('')).join('') + '</tr>';
  const nomes = Object.keys(D.modelos_sprint);
  tbody.innerHTML = '';
  nomes.forEach(nome => {{
    const tr = document.createElement('tr');
    const cells = [`<td style="font-family:var(--fm);font-weight:600">${{nome}}</td>`];
    alvos.forEach(([, dados]) => {{
      metricas.forEach(m => {{
        const v = dados[nome] ? (dados[nome][m] ?? '—') : '—';
        const isR2 = m === 'R2';
        const val  = typeof v === 'number' ? v.toFixed(isR2?3:1) : v;
        const cls  = (m===metrica)
          ? (isR2 ? (v>=0.5?'vn':v<0?'vp':'vm') : 'vm')
          : '';
        const hl   = m===metrica ? 'background:rgba(232,73,15,.06);' : '';
        cells.push(`<td class="${{cls}}" style="${{hl}}">${{val}}</td>`);
      }});
    }});
    tr.innerHTML = cells.join('');
    tbody.appendChild(tr);
  }});
}}

// Inicializar gráficos com MAE
modCharts['ch-mod-spr'] = buildModChart('ch-mod-spr', D.modelos_sprint, 2.2, 'MAE');
modCharts['ch-mod-dia'] = buildModChart('ch-mod-dia', D.modelos_dias,   1.8, 'MAE');
modCharts['ch-mod-pln'] = buildModChart('ch-mod-pln', D.modelos_plan,   1.6, 'MAE');
document.getElementById('metric-hint').textContent = METRIC_HINTS['MAE'];
buildTabMod('MAE');
// tabela
(function(){{
  const cols=['ID','Projeto','Tipo Obra','Área m²','Pts Prev','Pts Real','Var%','Spr Prev','Spr Exec','Var Spr%','Dias','Arq.R'];
  document.querySelector('#tab-p thead').innerHTML='<tr>'+cols.map(c=>`<th>${{c}}</th>`).join('')+'</tr>';
  const tb=document.querySelector('#tab-p tbody');
  D.tabela.forEach(r=>{{
    const cor=CORES_OBRA[r.tipo_obra]||'#888',vc=v=>v>10?'vp':v<-10?'vn':'vm';
    const tr=document.createElement('tr');
    tr.innerHTML=`<td style="font-family:var(--fm);font-weight:700">P${{r.id}}</td>
      <td style="font-family:var(--ff)">${{r.projeto}}</td>
      <td><span class="badge" style="background:${{cor}}20;color:${{cor}};border:1px solid ${{cor}}35">${{r.tipo_obra}}</span></td>
      <td>${{r.area}}</td><td>${{r.pts_prev}}</td><td>${{r.pts_real}}</td>
      <td class="${{vc(r.var_pts)}}">${{r.var_pts>0?'+':''}}${{r.var_pts}}%</td>
      <td>${{r.sprint_prev}}</td><td>${{r.sprint_exec}}</td>
      <td class="${{vc(r.var_sprint)}}">${{r.var_sprint>0?'+':''}}${{r.var_sprint}}%</td>
      <td>${{r.duracao}}</td>
      <td>${{r.arq_reaprov?'<span class="badge" style="background:rgba(58,124,165,.3);color:#3A7CA5">sim</span>':'—'}}</td>`;
    tb.appendChild(tr);
  }});
}})();
// predição
function getEnc(campo,val){{
  return D.cats_enc[campo]&&D.cats_enc[campo][val]!==undefined?D.cats_enc[campo][val]:0;
}}
function ridgePred(coef,feats){{
  if(!coef||!coef.coef) return null;
  let s=coef.intercept;
  const fL=mc.features||coef.features;
  const mA=mc.mean||coef.mean;
  const sA=mc.scale||coef.scale;
  fL.forEach((f,i)=>{{ s+=mc.coef[i]*(((feats[f]||0)-mA[i])/(sA[i]||1)); }});
  return Math.max(0,s);
}}
function ridgePlan(coef,feats){{
  if(!coef||!coef.modelos) return {{}};
  const res={{}};
  coef.alvos.forEach(alvo=>{{
    const mc=coef.modelos[alvo]; let s=mc.intercept;
    coef.features.forEach((f,i)=>{{ s+=mc.coef[i]*(((feats[f]||0)-coef.mean[i])/(coef.scale[i]||1)); }});
    res[alvo]=Math.max(0,s);
  }});
  return res;
}}
let piePredChart=null;
function calcularPredicao(){{
  const feats={{
    area:           parseFloat(document.getElementById('f_area').value)||0,
    benfeitoria_enc:getEnc('benfeitoria',document.getElementById('f_benf').value),
    tipo_om_enc:    getEnc('tipo_om',    document.getElementById('f_om').value),
    tipo_obra_enc:  getEnc('tipo_obra',  document.getElementById('f_obra').value),
    arq_reaprov:    document.getElementById('f_reaprov').checked?1:0,
  }};
  document.getElementById('f-spr').textContent=(ridgePred(D.coefs_dur_pre.sprint_exec,feats)||0).toFixed(1);
  document.getElementById('f-dia').textContent=Math.round(ridgePred(D.coefs_dur_pre.duracao_dias,feats)||0);
  const res=ridgePlan(D.coef_plan,feats);
  const idMap={{'pts_prev':'f-tot','ep_prev':'f-ep','ap_prev':'f-ap','pe_arq_prev':'f-pe-arq','pe_eng_prev':'f-pe-eng','orc_prev':'f-orc'}};
  for(const[k,v]of Object.entries(idMap)) document.getElementById(v).textContent=Math.round(res[k]||0);
  document.getElementById('pred-res').style.display='block';
  const etapas=['EP','AP','PE Arq','PE Eng','Orçamento'];
  const alvEt=['ep_prev','ap_prev','pe_arq_prev','pe_eng_prev','orc_prev'];
  const vals=alvEt.map(a=>Math.max(0,res[a]||0));
  const pC=['#1B3A5C','#E8490F','#2E8B57','#F4C430','#8B1A4A'];
  const total=vals.reduce((a,b)=>a+b,0);
  mkLegend('leg-pie',etapas.map((e,i)=>[`${{e}} — ${{Math.round(vals[i])}} pts`,pC[i]]));
  const ctx=document.getElementById('pred-pie').getContext('2d');
  if(piePredChart) piePredChart.destroy();
  piePredChart=new Chart(ctx,{{
    type:'doughnut',
    data:{{labels:etapas,datasets:[{{data:vals,backgroundColor:pC,borderColor:'#0d1117',borderWidth:2}}]}},
    options:{{responsive:true,maintainAspectRatio:true,aspectRatio:1.8,
      plugins:{{legend:{{display:false}},tooltip:{{callbacks:{{
        label:c=>` ${{c.label}}: ${{Math.round(c.raw)}} pts (${{total>0?((c.raw/total)*100).toFixed(1):0}}%)`
      }}}}}}}}
  }});
}}


// ═══════════════════════════════════════════════════════
// INICIALIZAÇÃO (script está no final do body — sem timing issue)
// ═══════════════════════════════════════════════════════

// Preenche selects da aba Planejamento
(function() {{
  if (!DA || !DA.encs) return;
  const fill = (id, cat) => {{
    const el = document.getElementById(id); if (!el) return;
    Object.keys(DA.encs[cat]).sort().forEach(v => {{
      const o = document.createElement('option'); o.value=v; o.textContent=v; el.appendChild(o);
    }});
  }};
  fill('pl_obra',   'tipo_obra');
  fill('pl_benf',   'benfeitoria');
  fill('pl_om',     'tipo_om');

  // Semáforo de confiança
  const sg = document.getElementById('pl-semaforo');
  const CC = {{'green':'#2E8B57','yellow':'#F4C430','red':'#ff6b6b'}};
  const NM = {{'EP':'Est. Preliminar','AP':'Anteprojeto','PE Arq':'PE Arquitetura',
               'PE Eng':'PE Engenharia','Orc':'Orçamento'}};
  Object.entries(DA.confianca||{{}}).forEach(([et,c]) => {{
    if (!NM[et]) return;
    const cor = CC[c.cor]||'#8b949e';
    const span = document.createElement('span');
    span.style.cssText=`display:inline-flex;align-items:center;gap:4px;font-size:.7rem;padding:2px 8px;border-radius:20px;border:1px solid ${{cor}}50;background:${{cor}}12;color:${{cor}}`;
    span.innerHTML = `<span style="width:7px;height:7px;border-radius:50%;background:${{cor}};flex-shrink:0"></span>${{NM[et]}} ${{c.mae_rel}}%`;
    sg && sg.appendChild(span);
  }});

  // LOO-MAE info in infobox — update sprint mae
  const m = DA.loo_mae||{{}};
  document.querySelectorAll('.plan-mae').forEach(el => {{
    el.textContent = `LOO-CV: sprint ±${{m.sprint_exec_media||'—'}} spr · pts ±${{m.pts_real||'—'}} pts`;
  }});
}})();

// Retrospectiva anual
(function() {{
  if (!ANUAL || !ANUAL.anos || !ANUAL.anos.length) return;
  const {{anos, por_ano, tendencia}} = ANUAL;

  // KPI cards por ano
  const body = document.getElementById('anual-body');
  if (body) {{
    anos.forEach(ano => {{
      const g = por_ano[ano];
      const cls = Math.abs(g.var_pts) > 20 ? 'yellow' : 'green';
      body.innerHTML += `
      <div class="kg" style="margin-bottom:1.25rem">
        <div class="kc" style="font-family:var(--fd);font-size:.8rem;color:var(--mu);grid-column:1/-1;padding:.25rem 0">
          Portfólio ${{ano}} — ${{g.n}} projeto${{g.n>1?'s':''}}
        </div>
        <div class="kc ${{cls}}"><div class="kl">Var. média pts</div>
          <div class="kv">${{g.var_pts>0?'+':''}}${{g.var_pts}}%</div></div>
        <div class="kc green"><div class="kl">Eficiência</div><div class="kv">${{g.efic}}</div></div>
        <div class="kc"><div class="kl">Estouro pts</div><div class="kv">${{g.estouro_pts}}%</div></div>
        <div class="kc"><div class="kl">Var. sprints</div>
          <div class="kv">${{g.var_sprint>0?'+':''}}${{g.var_sprint}}%</div></div>
        <div class="kc"><div class="kl">Duração média</div><div class="kv">${{g.duracao_med}}d</div></div>
      </div>`;
    }});
  }}

  // Gráfico variância por etapa
  const ctxA = document.getElementById('ch-anual');
  if (ctxA && anos.length) {{
    const etL = ['EP','AP','PE Arq','PE Eng','Orc'];
    new Chart(ctxA.getContext('2d'), {{
      type:'bar',
      data:{{
        labels:etL,
        datasets:anos.map((a,ai) => ({{
          label:a, borderRadius:3,
          data:etL.map(e => (por_ano[a].var_etapa||{{}})[e]||0),
          backgroundColor:PAL[ai]+'99', borderColor:PAL[ai], borderWidth:1.5
        }}))
      }},
      options:{{...BO, aspectRatio:1.6,
        plugins:{{legend:{{display:true, position:'top', labels:{{color:'#8b949e',boxWidth:10}}}}}},
        scales:{{x:{{...BO.scales.x}},y:{{...BO.scales.y}}}}
      }}
    }});
  }}

  // Tendência texto
  const tendEl = document.getElementById('tend-resumo');
  if (tendEl && Object.keys(tendencia).length) {{
    [
      {{k:'var_pts',    label:'Variância de Pontos',  melhor:v=>v<0, u:'pp'}},
      {{k:'var_sprint', label:'Variância de Sprints', melhor:v=>v<0, u:'pp'}},
      {{k:'estouro_pts',label:'Taxa Estouro Pontos',  melhor:v=>v<0, u:'pp'}},
      {{k:'efic',       label:'Índice de Eficiência', melhor:v=>v>0, u:''}},
    ].forEach(({{k,label,melhor,u}}) => {{
      const d = tendencia[k]; if (d===undefined) return;
      const bom = melhor(d), neutro = Math.abs(d)<0.05;
      const bg = neutro ? '#8b949e' : bom ? '#2E8B57' : '#ff6b6b';
      tendEl.innerHTML += `
      <div style="display:flex;justify-content:space-between;align-items:center;padding:.45rem 0;border-bottom:1px solid var(--br)">
        <span>${{label}}</span>
        <span style="font-family:var(--fm);font-size:.75rem;padding:2px 9px;border-radius:20px;
               background:${{bg}}18;border:1px solid ${{bg}}50;color:${{bg}}">
          ${{neutro?'→':bom?'↓ melhora':'↑ piora'}} ${{d>0?'+':''}}${{d}}${{u}}
        </span>
      </div>`;
    }});
  }}
}})();

// ── Planejar Projeto ─────────────────────────────────────────────────
function plAtualizarAP() {{
  const tp = document.getElementById('pl_obra').value;
  const el = document.getElementById('pl-ap-info'); if(!el) return;
  const MSGS = {{
    'nunca':    {{cls:'infobox',       txt:'ℹ️ <strong>AP</strong> não se aplica — vai direto EP → PE Arq.'}},
    'raramente':{{cls:'infobox yellow',txt:'💡 <strong>AP</strong> geralmente ausente neste tipo.'}},
    'frequente':{{cls:'infobox green', txt:'✅ <strong>AP</strong> geralmente presente.'}},
    'sempre':   {{cls:'infobox green', txt:'✅ <strong>AP</strong> sempre presente em Reformas.'}},
  }};
  const regra = (DA.ap_regra||{{}})[tp]||'frequente';
  const msg = MSGS[regra]; el.className=msg.cls; el.innerHTML=tp?msg.txt:'';
}}

function _plBuildVec(area,tipoObra,tipoBenf,tipoOM,nDisc,reaprov) {{
  const enc=DA.encs, nf=DA.n_feats, vec=[];
  [['tipo_obra',3,tipoObra],['benfeitoria',2,tipoBenf],['tipo_om',1,tipoOM]].forEach(([cat,peso,val])=>{{
    const n=nf[cat]||0;
    for(let i=0;i<n;i++) vec.push(((enc[cat]||{{}})[val]===i?1:0)*peso);
  }});
  const areaN=DA.area_max>DA.area_min?(area-DA.area_min)/(DA.area_max-DA.area_min):0.5;
  vec.push(areaN*2); vec.push(Math.max(0,Math.min(1,(nDisc-2)/6))*2); vec.push(reaprov*0.5);
  return vec;
}}
function _plCos(a,b){{let d=0,na=0,nb=0;for(let i=0;i<a.length;i++){{d+=a[i]*b[i];na+=a[i]*a[i];nb+=b[i]*b[i];}}return Math.sqrt(na)*Math.sqrt(nb)>0?d/(Math.sqrt(na)*Math.sqrt(nb)):0;}}
function _plSim(qv,k=3){{return (DA.vecs||[]).map((v,i)=>{{return{{i,sim:_plCos(qv,v)}};}} ).sort((a,b)=>b.sim-a.sim).slice(0,k);}}

let _plScChart=null;
function calcularPlano() {{
  const tipoObra=document.getElementById('pl_obra').value||'';
  const tipoBenf=document.getElementById('pl_benf').value||'';
  const tipoOM  =document.getElementById('pl_om').value||'';
  const area    =parseFloat(document.getElementById('pl_area').value)||0;
  const nDisc   =parseInt(document.getElementById('pl_n_disc').value)||6;
  const reaprov =document.getElementById('pl_reaprov').checked?1:0;
  const apRegra =(DA.ap_regra||{{}})[tipoObra]||'frequente';

  // Analogia
  const qv   = _plBuildVec(area,tipoObra,tipoBenf,tipoOM,nDisc,reaprov);
  const sims = _plSim(qv,3);
  const tw   = sims.reduce((s,x)=>s+x.sim,0)||1;
  const pred = {{pts_real:0,sprint_exec_media:0,ep_exec:0,ap_exec:0,pe_arq_exec:0,pe_eng_exec:0,orc_exec:0}};
  const sprints_list=[];
  sims.forEach(({{i,sim}})=>{{
    const w=sim/tw, p=(DA.projetos||[])[i]; if(!p) return;
    pred.pts_real+=w*p.pts_real; pred.sprint_exec_media+=w*p.sprint_exec;
    sprints_list.push(p.sprint_exec);
    ['ep_exec','ap_exec','pe_arq_exec','pe_eng_exec','orc_exec'].forEach(k=>{{pred[k]+=w*(p[k]||0);}});
  }});
  if(apRegra==='nunca'||apRegra==='raramente') pred.ap_exec=0;

  // Lasso points (from coef_plan)
  const coef=D.coef_plan;
  const feats={{area,tipo_obra_enc:getEnc('tipo_obra',tipoObra),arq_reaprov:reaprov,n_disc:nDisc}};
  const lassoPts=ridgePlan(coef,feats);

  document.getElementById('pl-resultado').style.display='block';

  // Grid de pontos (Lasso)
  const ET=[['EP','ep_prev'],['AP','ap_prev'],['PE Arq','pe_arq_prev'],['PE Eng','pe_eng_prev'],['Orc','orc_prev']];
  const CONF=DA.confianca||{{}};
  const CC={{'green':'#2E8B57','yellow':'#F4C430','red':'#ff6b6b'}};
  let gh=`<div class="pi"><div class="pn" style="color:var(--ac)">${{Math.round(lassoPts.pts_prev||pred.pts_real)}}</div><div class="pm">Pontos total (plano)</div></div>`;
  const isApSkip=apRegra==='nunca'||apRegra==='raramente';
  ET.forEach(([label,key])=>{{
    const isAP=label==='AP'&&isApSkip; const c=CONF[label]||{{}};
    const cor=CC[c.cor]||'#8b949e';
    const val=lassoPts[key]!=null?Math.round(lassoPts[key]):Math.round(pred[key.replace('_prev','_exec')]||0);
    gh+=`<div class="pi" style="${{isAP?'opacity:.35':''}}">
      <div class="pn" style="font-size:1.4rem;color:#3A7CA5">${{val}}</div>
      <div class="pm">${{label}}${{isAP?' <span style="font-size:.62rem;color:var(--mu)">(ausente)</span>':''}}</div>
      <div style="margin-top:.25rem;font-size:.68rem;color:${{cor}}">${{c.label||''}} ${{c.mae_rel!=null?'±'+c.mae_rel+'%':''}}</div>
    </div>`;
  }});
  document.getElementById('pl-pts-grid').innerHTML=gh;

  // Prazo (Motor de Analogia)
  const spMin=Math.min(...sprints_list)||0, spMax=Math.max(...sprints_list)||0;
  document.getElementById('pl-prazo-grid').innerHTML=`
    <div class="pi"><div class="pn" style="color:var(--ac)">${{Math.round(pred.sprint_exec_media)}}</div><div class="pm">Sprints (média análogos)</div></div>
    <div class="pi"><div class="pn">${{spMin}}</div><div class="pm">Sprints mínimo</div></div>
    <div class="pi"><div class="pn">${{spMax}}</div><div class="pm">Sprints máximo</div></div>
    <div class="pnote">1 sprint = 2 semanas · baseado em ${{sims.length}} projeto${{sims.length>1?'s':''}} análogo${{sims.length>1?'s':''}}</div>`;

  // Curva S
  const predTot=Math.max(1,pred.pts_real);
  const KEYS=['ep_exec','ap_exec','pe_arq_exec','pe_eng_exec','orc_exec'];
  const LABL=['após EP','após AP','após PE Arq','após PE Eng','após Orc'];
  const wC=new Array(5).fill(0);
  sims.forEach(({{i,sim}})=>{{
    const p=(DA.projetos||[])[i];if(!p)return;
    const pts=KEYS.map(k=>p[k]||0),tot=pts.reduce((a,b)=>a+b,0)||1;
    let cum=0; pts.forEach((v,j)=>{{cum+=v;wC[j]+=(sim/tw)*(cum/tot);}});
  }});
  const sCurve=wC.map(v=>Math.round(v*predTot));
  const scDS=[
    {{label:'Projetado',data:sCurve,borderColor:'#E8490F',borderWidth:2.5,fill:true,
      backgroundColor:'rgba(232,73,15,.07)',tension:.4,pointRadius:5,type:'line'}},
    ...sims.map(({{i,sim}},rk)=>{{
      const p=(DA.projetos||[])[i];if(!p)return null;
      const pts=KEYS.map(k=>p[k]||0),tot=pts.reduce((a,b)=>a+b,0)||1;
      let cum=0;
      return {{label:`P${{p.id}} (${{(sim*100).toFixed(0)}}%)`,type:'line',
        data:pts.map(v=>{{cum+=v;return Math.round(cum/tot*predTot);}}),
        borderColor:PAL[rk+2]+'99',borderWidth:1.5,fill:false,tension:.35,pointRadius:3,borderDash:[4,3]}};
    }}).filter(Boolean)
  ];
  mkLegend('leg-pl-sc',scDS.map(d=>[d.label,d.borderColor.replace('99','')]));
  const cSC=document.getElementById('ch-pl-sc').getContext('2d');
  if(_plScChart) _plScChart.destroy();
  _plScChart=new Chart(cSC,{{data:{{labels:LABL,datasets:scDS}},
    options:{{...BO,aspectRatio:1.8,plugins:{{legend:{{display:false}}}},
      scales:{{x:{{...BO.scales.x}},y:{{...BO.scales.y,title:{{display:true,text:'Pts acumulados',color:'#8b949e'}}}}}}}}}});

  // Alertas
  const alertEl=document.getElementById('pl-alertas'); alertEl.innerHTML='';
  const aMap=(DA.alertas||{{}})[tipoObra]||{{}};
  const alerts=Object.entries(aMap).filter(([,v])=>v.pct_estouro>=50||v.media_var>15)
    .sort(([,a],[,b])=>b.media_var-a.media_var);
  if(alerts.length){{
    alertEl.innerHTML='<p style="font-weight:600;font-size:.85rem;margin-bottom:.5rem">⚠ Alertas baseados no histórico</p>';
    alerts.forEach(([et,v])=>{{
      const alto=v.pct_estouro>=70||v.media_var>30;
      alertEl.innerHTML+=`<div style="display:flex;gap:.75rem;padding:.6rem .9rem;margin-bottom:.4rem;border-radius:8px;border:1px solid ${{alto?'rgba(255,107,107,.4)':'rgba(244,196,48,.4)'}};background:${{alto?'rgba(255,107,107,.07)':'rgba(244,196,48,.07)'}};font-size:.8rem">
        <span>${{alto?'🔴':'🟡'}}</span>
        <div><strong>Etapa ${{et}}</strong> — estourou em ${{v.pct_estouro}}% dos casos (n=${{v.n}}), variação média ${{v.media_var>0?'+':''}}${{v.media_var}}%</div>
      </div>`;
    }});
  }}

  // Análogos
  const simEl=document.getElementById('pl-similares'); simEl.innerHTML='';
  sims.forEach(({{i,sim}},rk)=>{{
    const p=(DA.projetos||[])[i];if(!p)return;
    simEl.innerHTML+=`<div style="background:var(--bg);border:1px solid var(--br);border-left:4px solid ${{['var(--ac)','var(--ye)','#3A7CA5'][rk]}};border-radius:10px;padding:.9rem 1.1rem;margin-bottom:.6rem">
      <div style="display:flex;justify-content:space-between;flex-wrap:wrap;gap:.4rem;margin-bottom:.4rem">
        <span style="font-weight:600;font-size:.88rem">P${{p.id}} · ${{p.proj}}</span>
        <span style="font-size:.74rem;padding:2px 9px;border-radius:20px;background:rgba(232,73,15,.12);border:1px solid rgba(232,73,15,.3);color:var(--ac)">${{(sim*100).toFixed(0)}}% similar</span>
      </div>
      <div style="display:flex;gap:.75rem;flex-wrap:wrap;font-size:.75rem;color:var(--mu)">
        <span>📐 ${{p.area}} m²</span><span>🏗 ${{p.tipo_obra}}</span><span>N_disc=${{p.n_disc}}</span>
        ${{p.arq_reaprov?'<span style="color:#3A7CA5">♻ Arq. reaprov.</span>':''}}
      </div>
      <div style="display:flex;gap:1.25rem;flex-wrap:wrap;margin-top:.5rem;padding-top:.5rem;border-top:1px solid var(--br)">
        ${{[['Pts exec',p.pts_real],['Sprints',p.sprint_exec],['PE Arq',p.pe_arq_exec],['PE Eng',p.pe_eng_exec],['Orc',p.orc_exec]].map(([l,v])=>`<div style="text-align:center"><div style="font-family:var(--fm);font-size:1.1rem;font-weight:700">${{v}}</div><div style="font-size:.68rem;color:var(--mu)">${{l}}</div></div>`).join('')}}
      </div>
    </div>`;
  }});
}}

  </script>
</body>
</html>
"""

"""## Main"""

def main():
    print("=" * 60)
    print("  ANÁLISE DE PROJETOS — GERADOR DE DASHBOARD")
    print("=" * 60)

    # 1. Carregar e processar dados
    df = carregar_dados()
    df = engenharia_features(df)

    # 2. Modelo 1: duração com features executadas (retrospectivo)
    X, y_sprints, y_dias, encoders = preparar_features(df)
    res_sprints, melhor_sprint, coef_sprints = treinar_modelos(
        X, y_sprints, "Sprints (features exec)")
    res_dias, melhor_dias, coef_dias = treinar_modelos(
        X, y_dias, "Dias (features exec)")

    # 3. Modelo 2: planejamento multi-output
    X_plan_loo, X_plan_pred, Y_plan, feat_loo, feat_pred, alvos_plan = \
        preparar_features_planejamento(df, encoders)
    res_plan, melhor_plan, coef_plan = treinar_modelo_planejamento(
        X_plan_loo, X_plan_pred, Y_plan, feat_loo, feat_pred, alvos_plan)

    # 4. Modelo 3: duração pré-projeto (para predição de novos projetos)
    coefs_dur_pre = treinar_modelo_duracao_pre(df, encoders)

    # 5. Motor de Analogia + Retrospectiva Anual
    print("\n🔍 Motor de Analogia (LOO-CV k=3)...")
    motor = MotorAnalogia().fit(df)
    motor_js = motor.exportar_js()
    m = motor_js["loo_mae"]
    print(f"   MAE: pts={m.get('pts_real','—')}  sprint={m.get('sprint_exec_media','—')}  PE Arq={m.get('pe_arq_exec','—')}")
    dados_anuais = construir_dados_anuais(df)

    # 6. Preparar dados e KPIs
    kpis = calcular_kpis(df)
    dados = preparar_dados_dashboard(
        df=df, kpis=kpis, encoders=encoders,
        res_sprints=res_sprints, res_dias=res_dias, res_plan=res_plan,
        coef_sprints=coef_sprints, coef_dias=coef_dias,
        coef_plan=coef_plan, coefs_dur_pre=coefs_dur_pre,
        motor_js=motor_js, dados_anuais=dados_anuais,
    )

    # 6. Gerar HTML
    print("\n🖥️  Gerando dashboard HTML (Chart.js)...")
    html_content = gerar_html(dados)

    # 7. Salvar e baixar
    nome_html = "dashboard_projetos.html"
    with open(nome_html, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"✅  Dashboard: {nome_html}  ({len(html_content)//1024} KB)")

    if EM_COLAB:
        colab_files.download(nome_html)
        display(IPY_HTML(f"""
        <div style="background:#1B3A5C;border-radius:8px;padding:1rem 1.5rem;
                    color:white;font-family:sans-serif;margin-top:1rem">
          <b>✅ Dashboard gerado!</b><br>
          O arquivo <code>{nome_html}</code> foi baixado automaticamente.<br>
          Abra-o em qualquer navegador — funciona offline (após carregamento do CDN).
        </div>
        """))
    else:
        print(f"  Abra no navegador: file://{Path(nome_html).resolve()}")


if __name__ == "__main__":
    main()